STRINGS = {
    "app_name": "RelChat",
    "main_title": "RelChat",
    "main_connected": "Telegram connected",
    "main_not_connected": "Telegram not connected",
    "main_saved_chats": "Saved chats",
    "main_reports": "Reports",
    "main_followups": "Follow-ups",
    "main_running": "Analysis running",
    "main_idle": "No analysis running",
    "button_analyze": "Analyze a chat",
    "button_my_chats": "My chats",
    "button_reports": "Reports",
    "button_reminders": "Follow-ups",
    "button_settings": "Settings",
    "button_help": "Help",
    "button_back": "Back",
    "button_cancel": "Cancel",
    "button_main": "Main menu",
    "button_retry": "Retry",
    "button_run_analysis": "Run analysis",
    "button_update_analysis": "Update analysis",
    "button_analyze_again": "Analyze again",
    "button_overview": "Overview",
    "button_insights": "Insights",
    "button_timeline": "Timeline",
    "button_activity": "Activity",
    "button_response": "Response rhythm",
    "button_followups": "Follow-ups",
    "button_habits": "Habits",
    "button_chat_reports": "Reports for this chat",
    "button_chat_reports_short": "Reports",
    "button_chat_settings": "Chat settings",
    "button_delete_local_data": "Delete Local Data",
    "button_chat_home": "Chat Home",
    "button_details": "Details",
    "button_browse_timeline": "Browse timeline",
    "button_timeline_chart": "Activity chart",
    "button_newer": "Newer",
    "button_older": "Older",
    "button_latest_report": "Latest report",
    "button_favorite": "Favorite",
    "button_unfavorite": "Unfavorite",
    "button_rename": "Rename",
    "button_open_chat": "Open chat",
    "button_browse_all": "Browse all chats",
    "button_favorites": "Favorites",
    "button_recently_analyzed": "Recently analyzed",
    "button_saved_chats": "Saved chats",
    "onboarding_1_title": "Welcome to RelChat",
    "onboarding_1_body": "RelChat helps you review selected conversations using local metrics, events, reports, and reminders.",
    "onboarding_2_title": "Privacy model",
    "onboarding_2_body": "Your chat history is read locally through your own Telegram account. The bot itself cannot read private chats through the Bot API.",
    "onboarding_3_connected": "Telegram connected. You can continue to the main menu.",
    "onboarding_3_missing": "Telegram is not connected yet. One local Telegram authorization is required before RelChat can load chats.",
    "onboarding_safe_auth": "Do not send login codes, passwords, API hashes, bot tokens, session files, or phone numbers here.",
    "help_title": "Help",
    "privacy_title": "How privacy works",
    "auth_title": "Why authorization is required",
    "metrics_title": "What metrics mean",
    "limits_title": "What RelChat cannot know",
    "troubleshooting_title": "Troubleshooting",
    "about_title": "About",
    "empty": "Nothing to show yet.",
    "empty_no_analyzed_chats": "No analyzed chats yet. Analyze a chat to create the first Chat Home.",
    "empty_no_recent_chats": "No recently analyzed chats yet.",
    "empty_no_report": "No report exists for this chat yet. Run an analysis to create a snapshot and report.",
    "empty_no_followups": "No follow-ups for this chat yet.",
    "loading_chats": "Loading chats...",
    "loading_chat_home": "Loading chat summary...",
    "loading_failed": "Could not load chats. Check the local Telegram connection and try again.",
    "session_missing": "Telegram is not connected locally yet. Complete the local Telegram authorization first, then return here.",
    "auth_expired": "Telegram authorization appears to have expired. Reconnect locally, then try again.",
    "network_unavailable": "Telegram is unreachable right now. Check the network connection and try again.",
    "flood_wait": "Telegram asked RelChat to wait before continuing. Try again later.",
    "chat_inaccessible": "This chat is not accessible through the connected Telegram account.",
    "expired_navigation": "This screen is no longer available. Return to the main menu and open the chat again.",
    "unknown_action": "That action is no longer available. Return to the main menu.",
    "analysis_already_running": "An analysis is already running for this chat.",
    "no_messages": "No messages were found for the selected period.",
    "invalid_date": "I could not read that date. Try 2026-07-01, 01.07.2026, 7 days, or 30 days.",
    "cancelled": "Analysis cancelled. Imported local messages were kept safely, and no completed report was created.",
    "database_problem": "Local storage had a problem. Try again after checking the local database.",
    "unexpected_error": "Something went wrong. Error reference: {reference}",
    "destructive_note": "This only affects local RelChat data. It never deletes Telegram chats or messages.",
    "chat_type_person": "Person",
    "chat_type_group": "Group",
    "chat_type_channel": "Channel",
    "chat_type_unknown": "Chat",
    "chat_home_current": "Current snapshot",
    "chat_home_changed": "Changed recently",
    "chat_home_attention": "Needs attention",
    "chat_home_explore": "Explore",
    "chat_home_data_quality": "Data quality",
    "chat_home_no_analysis": "No analysis yet.",
    "chat_home_no_analysis_action": "Run an analysis to create a snapshot, report, timeline, and follow-up list.",
    "chat_home_last_period": "Last analyzed period",
    "chat_home_report_freshness": "Report freshness",
    "chat_home_pending_followups": "Pending follow-ups",
    "chat_home_running": "Analysis is currently running for this chat.",
    "chat_home_v4_state_stable": "Everything looks stable.",
    "chat_home_v4_state_group_stable": "Group activity looks stable.",
    "chat_home_v4_state_channel_stable": "Posting activity looks stable.",
    "chat_home_v4_state_attention": "A few items may need your attention.",
    "chat_home_v4_state_long_silence": "No communication for several days.",
    "chat_home_v4_state_group_long_silence": "No group activity for several days.",
    "chat_home_v4_state_channel_long_silence": "No channel posts for several days.",
    "chat_home_v4_state_quiet": "Communication is quieter than the previous period.",
    "chat_home_v4_state_group_quiet": "Group activity is quieter than the previous period.",
    "chat_home_v4_state_channel_quiet": "Posting activity is quieter than the previous period.",
    "chat_home_v4_state_active": "Communication is more active than before.",
    "chat_home_v4_state_group_active": "Group activity is higher than before.",
    "chat_home_v4_state_channel_active": "Posting activity is higher than before.",
    "chat_home_v4_state_no_analysis": "No analysis yet.",
    "chat_home_v4_state_running": "Analysis is running now.",
    "chat_home_v4_last_activity": "Last activity",
    "chat_home_v4_communication_rhythm": "Communication rhythm",
    "chat_home_v4_group_rhythm": "Group activity rhythm",
    "chat_home_v4_posting_cadence": "Posting cadence",
    "chat_home_v4_current_activity": "Current activity",
    "chat_home_v4_current_group_activity": "Current group activity",
    "chat_home_v4_current_posting": "Current posting activity",
    "chat_home_v4_next_reminder": "Next reminder",
    "chat_home_v4_last_analysis": "Last analysis",
    "chat_home_v4_trend": "Trend",
    "chat_home_v4_attention_section": "Attention",
    "chat_home_v4_latest_analysis_section": "Latest analysis",
    "chat_home_v4_latest_analysis_value": "Updated",
    "chat_home_v4_followup_title": "Follow-up",
    "chat_home_v4_followups_count": "{count} follow-ups",
    "chat_home_v4_no_followups_value": "No follow-ups suggested yet.",
    "chat_home_v4_no_reminder_value": "No reminder scheduled.",
    "chat_home_v4_no_analysis_title": "No analysis yet.",
    "chat_home_v4_no_analysis_body": "Run your first analysis to see communication insights.",
    "chat_home_v4_rhythm_regular": "Regular",
    "chat_home_v4_rhythm_bursty": "Bursty",
    "chat_home_v4_rhythm_quiet": "Quiet",
    "chat_home_v4_cadence_regular": "Regular",
    "chat_home_v4_cadence_bursty": "Bursty",
    "chat_home_v4_cadence_quiet": "Quiet",
    "chat_home_v4_unknown": "Not enough data yet",
    "chat_home_v4_activity_up": "Higher than the previous period",
    "chat_home_v4_activity_stable": "Similar to the previous period",
    "chat_home_v4_activity_down": "Lower than the previous period",
    "chat_home_v4_posting_up": "More posts than the previous period",
    "chat_home_v4_posting_stable": "Similar to the previous period",
    "chat_home_v4_posting_down": "Fewer posts than the previous period",
    "chat_home_v4_recent_unknown": "No comparable previous period yet",
    "chat_home_v4_initiation_one_sided": "One participant starts most sessions.",
    "chat_home_v4_initiation_balanced": "Session starts are fairly balanced.",
    "chat_home_v4_group_initiation_balanced": "Several participants start active periods.",
    "chat_home_v4_reply_limited": "Not enough reply data yet.",
    "chat_home_v4_reply_observed": "Replies were observed in this period.",
    "chat_home_v4_not_used_for_channels": "Not used for channels.",
    "chat_home_loading_title": "Loading chat...",
    "chat_home_loading_chat": "Loading chat",
    "chat_home_loading_report": "Loading latest report",
    "chat_home_loading_reminders": "Loading reminders",
    "status_active": "Active",
    "status_quiet": "Quiet",
    "status_attention": "Needs attention",
    "status_long_silence": "Long silence",
    "status_no_analysis": "No analysis",
    "status_loading": "Loading",
    "confidence_high": "High",
    "confidence_medium": "Medium",
    "confidence_low": "Low",
    "chat_settings_title": "Chat settings",
    "chat_settings_body": "These are local RelChat settings for this chat. They do not change Telegram chats or messages.",
    "chat_settings_manage_hint": "Use My chats to rename locally, favorite, or remove local RelChat data.",
    "chat_settings_favorite": "Favorite",
    "yes": "yes",
    "no": "no",
    "relative_today": "Today",
    "relative_yesterday": "Yesterday",
    "relative_tomorrow": "Tomorrow",
    "relative_days_ago": "{count} days ago",
    "relative_in_days": "in {count} days",
    "chat_summary_private": "This summary is based on observable communication patterns only.",
    "chat_summary_group": "This group summary focuses on activity, participation, questions, plans, and follow-ups.",
    "chat_summary_channel": "This channel summary focuses on publishing activity, quiet periods, and content cadence.",
    "chat_summary_messages": "Messages in latest report",
    "chat_changed_unavailable": "Trend comparison is not available yet.",
    "chat_attention_clear": "No follow-ups need attention right now.",
    "chat_attention_questions": "Questions that may need a response",
    "overview_title": "Overview",
    "overview_current_snapshot": "Current snapshot",
    "overview_recent_change": "Recent change",
    "overview_balance": "Balance",
    "overview_response": "Response rhythm",
    "overview_attention": "Needs attention",
    "overview_data_quality": "Data quality",
    "overview_details_title": "Overview details",
    "overview_no_report": "No completed report exists for this chat yet.",
    "overview_no_messages": "There are no analyzed messages in this report.",
    "overview_private_balanced": "Both people contributed at a similar level in this period.",
    "overview_private_one_sided_initiation": "The conversation has replies when active, while one participant starts most sessions.",
    "overview_private_active": "The conversation has enough activity to summarize observable communication patterns.",
    "overview_group": "This group was active enough to summarize participation, questions, plans, and follow-ups.",
    "overview_channel": "This channel overview focuses on posting activity and content cadence, not replies.",
    "overview_limited_sample": "The sample is limited, so RelChat avoids percentage-based conclusions.",
    "overview_recent_missing": "No comparable previous period is available yet.",
    "overview_recent_limited": "A previous report exists, but there is not enough comparable data to describe a change.",
    "overview_recent_similar": "Activity looks similar to the previous comparable period.",
    "overview_recent_higher": "Activity is higher than the previous comparable period.",
    "overview_recent_lower": "Activity is lower than the previous comparable period.",
    "overview_initiation_split": "Session starts",
    "overview_reply_participation": "Reply participation",
    "overview_planning_balance_unavailable": "Planning and follow-up participation by person is not available in this report.",
    "overview_typical_response": "Typical response time",
    "overview_active_response": "Active-chat response time",
    "overview_consistency": "Consistency",
    "overview_consistent": "Response rhythm looks fairly consistent in this period.",
    "overview_varied": "Response rhythm varies noticeably in this period.",
    "overview_response_limited": "There is not enough alternating-message data to summarize response rhythm.",
    "overview_no_attention": "No unresolved questions, plans, promises, or confirmed reminders need attention right now.",
    "overview_unanswered_questions": "Unanswered questions",
    "overview_unresolved_plans": "Plans to review",
    "overview_promises_followups": "Promises and follow-ups",
    "overview_confirmed_reminders": "Confirmed reminders",
    "overview_long_silences": "Quiet periods",
    "overview_average_length": "Average message length",
    "overview_imported_range": "Imported range",
    "overview_limitations": "Limitations",
    "overview_not_enough_for_percent": "Counts are shown without percentages because the sample is small.",
    "overview_count": "count",
    "not_available": "not available",
    "button_full_analysis": "Full analysis",
    "button_ai_analysis": "AI-enhanced analysis",
    "button_local_analysis": "Local analysis",
    "button_continue_ai": "Continue with AI",
    "button_use_local_analysis": "Use local analysis",
    "button_revoke_ai_consent": "Revoke AI consent",
    "button_result_details": "Details",
    "analysis_result_title": "Analysis complete",
    "analysis_result_local_mode": "Local analysis",
    "analysis_result_period": "Period",
    "analysis_result_messages": "Messages analyzed",
    "analysis_result_stands_out": "What stands out",
    "analysis_result_attention": "Needs attention",
    "analysis_result_quality": "Data quality",
    "analysis_result_ai_partial": "AI-enhanced analysis was unavailable, so this result uses local analysis.",
    "analysis_mode_title": "Choose analysis type",
    "analysis_mode_body": "Local analysis stays on this machine. AI-enhanced analysis can add a communication-style summary after you consent.",
    "ai_consent_prompt": "AI-enhanced analysis sends the selected conversation messages to OpenAI.\nYou can continue with local-only analysis instead.",
    "ai_error_disabled": "AI-enhanced analysis is currently disabled.",
    "ai_error_missing_key": "AI-enhanced analysis is not configured because the OpenAI API key is missing.",
    "ai_error_missing_model": "AI-enhanced analysis is not configured because the model name is missing.",
    "ai_error_sdk_missing": "AI-enhanced analysis needs the optional OpenAI Python SDK.",
    "ai_error_generic": "AI-enhanced analysis is unavailable right now.",
    "ai_error_failed": "AI-enhanced analysis failed safely. Local analysis is still available.",
    "ai_offer_local": "You can continue with local-only analysis instead.",
    "ai_communication_analysis": "Communication analysis",
    "ai_activity_analysis": "Activity analysis",
    "ai_communication_score": "Communication score",
    "ai_effectiveness_score": "Effectiveness score",
    "ai_activity_score": "Activity score",
    "ai_confidence_line": "Confidence: {confidence}",
    "ai_confidence_short": "Confidence",
    "ai_summary_title": "Summary",
    "ai_strengths_title": "Strong sides",
    "ai_weakens_title": "What weakens it",
    "ai_main_advice": "Main advice",
    "ai_advice_title": "Advice",
    "ai_weak_replies_title": "Replies that weakened the conversation",
    "ai_scores_title": "Scores",
    "ai_example": "Example",
    "ai_no_raw_text_note": "Raw message text is hidden by default.",
    "ai_no_weak_replies": "No weakened-reply patterns were found in this result.",
    "ai_severity": "Severity",
    "ai_reference": "Reference",
    "ai_local_reference": "local candidate",
    "ai_score_formula": "Overall score = weighted positive communication dimensions minus risk penalties, clamped to 0-10.",
    "ai_insufficient_data": "Insufficient data",
    "ai_score_unreliable": "Insufficient data for a reliable overall score",
    "ai_score_insufficient_explanation": "There is not enough comparable evidence for a reliable score.",
    "ai_score_cap_shallow": "The score is capped because only shallow local structure is available.",
    "ai_score_cap_deterministic": "The score is capped because deterministic metrics do not understand message meaning.",
    "ai_score_cap_sampled_ai": "The score is capped because AI interpretation used a sample rather than full text coverage.",
    "ai_score_cap_context": "The score is capped because the communication context has low confidence.",
    "ai_score_cap_limited_dimensions": "The score is capped because too few independent dimensions are supported.",
    "ai_data_title": "Data",
    "ai_coverage_messages": "Analyzed {count} messages in the selected period.",
    "ai_selected_period_analyzed": "Analyzed the selected period.",
    "ai_sample_used": "A message sample was used for part of the analysis.",
    "ai_sample_used_count": "A sample of {count} messages was used for part of the analysis.",
    "ai_evidence_count": "Evidence",
    "ai_limitations_title": "Limitations",
    "ai_full_analysis_title": "Full analysis",
    "ai_you_title": "How you communicate",
    "ai_other_title": "How the other person communicates",
    "ai_consent_status": "AI consent",
    "settings_ai_consent_active": "active",
    "settings_ai_consent_not_active": "not active",
    "ai_consent_revoked": "AI consent was revoked. Future AI-enhanced analyses will ask again before sending selected messages to OpenAI.",
    "ai_dimension_reciprocity": "Reciprocity",
    "ai_dimension_initiative_balance": "Initiative",
    "ai_dimension_reply_consistency": "Reply consistency",
    "ai_dimension_reply_quality": "Reply quality",
    "ai_dimension_respectfulness": "Respectfulness",
    "ai_dimension_topic_continuation": "Topic continuation",
    "ai_dimension_question_engagement": "Question engagement",
    "ai_dimension_planning_cooperation": "Planning cooperation",
    "ai_dimension_emotional_acknowledgement": "Emotional acknowledgement",
    "ai_dimension_pressure_risk": "Pressure risk",
    "ai_dimension_hostility": "Hostility",
    "ai_dimension_dismissiveness": "Dismissiveness",
    "ai_dimension_unresolved_question_rate": "Unanswered questions",
    "ai_dimension_unanswered_question_rate": "Unanswered questions",
    "ai_dimension_sarcasm_intensity": "Sarcasm intensity",
    "ai_dimension_unavailable": "This dimension needs text interpretation.",
    "ai_sarcasm_unavailable": "Not enough data to assess sarcasm.",
    "ai_hostility_unavailable": "Not enough data to assess hostility.",
    "ai_dismissiveness_unavailable": "Not enough data to assess dismissive wording.",
    "ai_dimension_reciprocity_explanation": "Shows visible activity balance. It does not prove equal interest, warmth, or communication quality.",
    "ai_dimension_initiative_balance_explanation": "Shows who starts visible sessions. It does not explain why one side starts more often.",
    "ai_dimension_reply_consistency_explanation": "Shows available reply timing and alternating messages.",
    "ai_dimension_reply_quality_explanation": "Uses unanswered-question candidates and reply opportunities; local mode cannot judge the full meaning of each answer.",
    "ai_dimension_topic_continuation_explanation": "Shows repeated visible sessions and continuation opportunities.",
    "ai_dimension_question_engagement_explanation": "Shows how many question candidates received visible responses.",
    "ai_dimension_planning_cooperation_explanation": "Shows plan, promise, and follow-up candidates.",
    "ai_dimension_pressure_risk_explanation": "Shows pressure risk from repeated follow-up and promise candidates.",
    "severity_low": "low",
    "severity_medium": "medium",
    "severity_high": "high",
    "ai_weak_ignored_question": "Direct question ignored",
    "ai_weak_abrupt_reply": "Abrupt reply",
    "ai_weak_sarcasm": "Sarcasm replacing a direct answer",
    "ai_weak_sarcasm_instead_of_answer": "Sarcasm replacing a direct answer",
    "ai_weak_dismissive": "Dismissive wording",
    "ai_weak_topic_switch": "Abrupt topic change",
    "ai_weak_low_effort": "Low-effort reply",
    "ai_weak_hostile": "Hostile wording",
    "ai_weak_pressure": "Response that increases pressure",
    "ai_weak_missing_acknowledgement": "Important statement not acknowledged",
    "chat_home_details_title": "Details",
    "chat_home_details_body": "Open the full analysis, timeline, activity, follow-ups, previous analyses, or local chat settings.",
    "button_change_context": "Change communication type",
    "context_change_title": "Change communication type",
    "context_change_body": "Choose the context that best fits this chat. Your choice overrides automatic classification until you change it.",
    "context_saved": "Communication type saved.",
    "context_rerun_hint": "Run analysis again to apply it to a new result.",
    "context_option_romantic": "Romantic",
    "context_option_friendship": "Friendship",
    "context_option_family": "Family",
    "context_option_work": "Work",
    "context_option_other": "Other",
    "context_romantic": "Romantic communication",
    "context_friendship": "Friendship communication",
    "context_family": "Family communication",
    "context_work": "Work communication",
    "context_customer_or_service": "Customer or service communication",
    "context_group_social": "Group activity",
    "context_channel_or_broadcast": "Channel or broadcast activity",
    "context_mixed": "Mixed communication context",
    "context_unknown": "Communication context unknown",
    "context_low_confidence_note": "The communication context was estimated with low confidence.",
    "local_context_explanation": "The context was selected or estimated before analysis.",
    "local_limitation_structure": "Local analysis sees conversation structure, but does not understand the meaning of every reply.",
    "local_limitation_period": "Used local deterministic metrics for {period}.",
    "local_uncertainty_reason": "The reason cannot be determined from messages alone.",
    "local_uncertainty_no_ai": "No AI text interpretation was used.",
    "local_summary_no_activity": "There is not enough visible activity to support a communication conclusion.",
    "local_summary_group": "Group activity was summarized from local message counts, questions, plans, and follow-up candidates.",
    "local_summary_channel": "Channel activity was summarized from local posting cadence and quiet periods.",
    "local_summary_unanswered": "{count} direct question candidate(s) received no visible response inside the local response window.",
    "local_summary_private_neutral": "The conversation has visible activity, but local analysis only sees structure. Equal activity does not prove warmth, interest, respectfulness, or strong communication.",
    "local_summary_romantic_neutral": "The conversation has visible activity, but local analysis cannot reliably determine romantic interest or emotional warmth without text interpretation.",
    "local_summary_work_neutral": "The work conversation is active enough to summarize structure, but local analysis cannot judge whether replies actually resolved the task.",
    "local_pattern_visible_activity": "Visible activity",
    "local_pattern_visible_activity_explanation": "The selected period contains enough local activity to summarize basic patterns.",
    "local_pattern_both_sides": "Both sides participated",
    "local_pattern_visible_conversation": "Visible conversation activity",
    "local_pattern_activity_explanation": "Local metrics found message activity in the selected period.",
    "local_pattern_work_activity_explanation": "Local metrics found task-related activity, but not whether the work was resolved.",
    "local_problem_unanswered_title": "Unanswered questions",
    "local_problem_unanswered_explanation": "{count} direct question candidate(s) received no visible response inside the local response window.",
    "local_problem_followups_title": "Open follow-ups",
    "local_problem_followups_explanation": "{count} follow-up candidate(s) remained visible in this period.",
    "local_weak_ignored_question": "At least one direct question candidate did not receive a visible response inside the local response window.",
    "local_advice_question_title": "Ask one clear question",
    "local_advice_question_explanation": "A single specific question is easier to answer and easier to follow up on.",
    "local_advice_question_example": "Could you confirm the plan for Friday?",
    "local_advice_next_step_title": "Clarify the next step",
    "local_advice_next_step_explanation": "When plans or promises are open, a direct check-in is clearer than repeated reminders.",
    "local_advice_next_step_example": "Is this still convenient for tomorrow?",
    "local_advice_work_title": "Make the next step explicit",
    "local_advice_work_explanation": "State the task, owner, expected result, and deadline in one message.",
    "local_advice_work_example": "Task: send the final file. Owner: Alex. Deadline: Friday 16:00.",
    "local_advice_simple_title": "Keep the next message simple",
    "local_advice_simple_explanation": "Continue with one clear topic and watch whether the other participant also develops the conversation.",
    "local_advice_simple_example": "How does Thursday evening work for you?",
    "local_verdict_uneven_headline": "The conversation was uneven.",
    "local_verdict_uneven_explanation": "Local metrics show one side carried more visible activity or several direct questions received no visible response.",
    "local_verdict_strong_headline": "The visible communication was strong.",
    "local_verdict_strong_explanation": "This verdict requires several supported dimensions, not message volume alone.",
    "local_verdict_good_headline": "The visible communication was generally good.",
    "local_verdict_good_explanation": "This verdict is based on supported visible dimensions and remains limited by local evidence.",
    "local_verdict_mixed_headline": "The visible communication was mixed.",
    "local_verdict_mixed_explanation": "Some structural signs are positive, but the evidence does not support a strong conclusion.",
    "local_verdict_weak_headline": "The visible communication was weak.",
    "local_verdict_weak_explanation": "Visible metrics show weak or uneven communication behavior.",
    "local_verdict_very_weak_headline": "The visible communication was very weak.",
    "local_verdict_very_weak_explanation": "Visible metrics show several weak communication signals.",
    "local_verdict_insufficient_data_headline": "Insufficient comparable evidence.",
    "local_verdict_insufficient_data_explanation": "The visible data is too limited for a stable conclusion.",
    "local_finding_insufficient": "The visible data is too limited for a stable conclusion.",
    "local_finding_volume_unbalanced": "The dialogue was unbalanced. {side} carried most visible message volume.",
    "local_finding_no_restart": "{side} did not restart the conversation during this period.",
    "local_finding_equal_volume_not_quality": "Both sides wrote at a similar visible volume. This shows activity balance, not equal interest or communication quality.",
    "local_finding_unanswered": "{count} direct question candidate(s) received no visible response.",
    "local_finding_followups": "{count} follow-up candidate(s) remained visible in the selected period.",
    "local_finding_no_positive_conclusion": "The visible data does not support a positive communication conclusion for this period.",
    "local_finding_work_limited": "The work chat has visible activity, but local metrics cannot confirm whether the task was resolved.",
    "local_side_you": "You",
    "local_side_other": "The other participant",
    "local_recommendation_insufficient": "There is not enough visible data for a specific recommendation.",
    "local_recommendation_work_clarify": "Clarify the task, responsible person, expected result, and deadline in one message.",
    "local_recommendation_stop_repeating": "Do not send several new messages about the same unresolved point. Ask one direct question or wait for reciprocal initiative.",
    "local_recommendation_reduce_pressure": "Visible engagement was low or uneven, so adding pressure is unlikely to improve clarity.",
    "local_recommendation_work_next": "Keep the next work message concrete and assign the next step clearly.",
    "local_recommendation_continue": "Continue with clear, direct messages and watch whether the other participant also develops topics.",
    "local_strength_comparable_volume": "Participates at a comparable visible message volume.",
    "local_participant_summary_insufficient": "Not enough visible messages to summarize.",
    "local_participant_summary_none": "No visible messages from this side in the selected period.",
    "local_participant_summary_count": "{count} visible message(s) in the selected period.",
    "local_participant_pattern_none": "No visible messages from this side in the selected period.",
    "local_participant_pattern_carries_volume": "Carries most visible message volume in this period.",
    "local_participant_pattern_fewer_messages": "Participates with fewer visible messages in this period.",
    "local_participant_pattern_work_equal_volume": "Participates at a similar visible message volume; this does not prove the work was resolved.",
    "local_participant_pattern_similar_volume": "Participates at a similar visible message volume.",
    "local_improvement_one_question": "Ask one clear question at a time when you need a direct answer.",
    "local_improvement_answer_questions": "Answer direct questions clearly when a response is visible in the conversation.",
    "response_bucket_minutes": "within a few minutes",
    "response_bucket_hour": "within about an hour",
    "response_bucket_hours": "within a few hours",
    "response_bucket_day": "within the same day",
    "response_bucket_over_day": "over a day",
    "chat_reports_title": "Reports for this chat",
    "my_chats_title": "My chats",
    "my_chats_choose": "Choose a chat.",
    "my_chats_choose_section": "Choose a section.",
    "my_chats_favorites": "Favorites",
    "my_chats_recent": "Recently analyzed",
    "my_chats_saved": "Saved chats",
    "module_coming_soon": "Coming soon",
    "module_experimental": "Experimental",
    "module_not_included": "Not included in this report",
    "section_timeline_title": "Timeline",
    "section_activity_title": "Activity",
    "section_response_title": "Response rhythm",
    "section_followups_title": "Follow-ups",
    "section_habits_title": "Habits",
    "section_reports_title": "Reports",
    "section_unavailable_body": "This screen is prepared for Product UX v3, but this calculation is not available in the selected report.",
    "section_coming_soon_body": "This section is prepared for a future release and does not show generated results yet.",
    "section_channel_hidden_body": "This section is hidden for channels because reply rhythm and initiation balance are not meaningful without imported replies.",
    "selected_prefix": "Selected:",
    "timeline_private_note": "Shows observable communication rhythm between two participants. It does not infer feelings or intentions.",
    "timeline_group_note": "Shows group activity, quiet periods, questions, plans, and follow-ups without relationship wording.",
    "timeline_channel_note": "Shows publishing activity and quiet periods. Reply balance and initiation are hidden for channels.",
    "timeline_empty": "No timeline data is available yet. Run an analysis after importing messages to create activity periods and event markers.",
    "timeline_privacy_note": "No raw message text is shown in timeline entries.",
    "timeline_analyzed_period": "Analyzed period",
    "timeline_most_active": "Most active period",
    "timeline_longest_silence": "Longest silence",
    "timeline_meaningful_events": "Meaningful events",
    "timeline_recent_change": "Recent change",
    "timeline_recent_higher": "Activity increased compared with the previous active period.",
    "timeline_recent_lower": "Activity decreased compared with the previous active period.",
    "timeline_recent_similar": "Activity looks similar to the previous active period.",
    "timeline_recent_limited": "Recent change needs more messages before comparing.",
    "timeline_recent_unavailable": "Not enough timeline history to compare yet.",
    "timeline_filter": "Filter",
    "timeline_filter_all": "All",
    "timeline_filter_activity": "Activity",
    "timeline_filter_questions": "Questions",
    "timeline_filter_plans": "Plans",
    "timeline_filter_followups": "Follow-ups",
    "timeline_filter_silences": "Silences",
    "timeline_empty_filter": "No timeline entries match this filter yet.",
    "timeline_no_entries": "No entries",
    "timeline_showing": "Showing",
    "timeline_event_activity": "Activity period",
    "timeline_event_quiet": "Quiet period",
    "timeline_event_silence": "Long silence",
    "timeline_event_question": "Question detected",
    "timeline_event_unanswered": "Question may need a response",
    "timeline_event_plan": "Plan candidate",
    "timeline_event_promise": "Promise candidate",
    "timeline_event_followup": "Follow-up candidate",
    "timeline_event_reminder": "Confirmed reminder",
    "timeline_event_analysis": "Analysis completed",
    "timeline_sender": "Sender",
    "timeline_participant": "Participant",
    "timeline_member": "Member",
    "timeline_period": "Period",
    "timeline_gap": "Gap",
    "timeline_report_period": "Report period",
    "timeline_source_message": "Message marker",
    "timeline_rule_source": "Detected by",
    "timeline_chart_caption": "RelChat activity chart. No message text is included.",
    "timeline_chart_failed": "Could not create the activity chart right now. The text timeline is still available.",
    "timeline_empty_story": "No timeline story is available yet. Run an analysis after importing messages to see how activity changed over time.",
    "timeline_story_conversation_active": "Conversation active",
    "timeline_story_group_active": "Group active",
    "timeline_story_channel_active": "Channel active",
    "timeline_story_activity_body": "{messages} across {periods}",
    "timeline_story_activity_channel_body": "{posts} across {periods}",
    "timeline_count_message_one": "1 message",
    "timeline_count_message_many": "{count} messages",
    "timeline_count_post_one": "1 post",
    "timeline_count_post_many": "{count} posts",
    "timeline_count_period_one": "1 active period",
    "timeline_count_period_many": "{count} active periods",
    "timeline_story_resumed": "Conversation resumed",
    "timeline_story_resumed_body": "Activity returned after {days} quiet days",
    "timeline_story_quiet_period": "Long quiet period",
    "timeline_story_quiet_body": "No visible messages for {days} days",
    "timeline_story_activity_increased": "Activity increased",
    "timeline_story_activity_increased_body": "More active than the previous comparable period",
    "timeline_story_activity_decreased": "Activity decreased",
    "timeline_story_activity_decreased_body": "Quieter than the previous comparable period",
    "timeline_story_question": "Question detected",
    "timeline_story_question_body": "A question appeared in the conversation",
    "timeline_story_unanswered_question": "Question may need a response",
    "timeline_story_unanswered_question_body": "One open question may need attention",
    "timeline_story_plan": "Plan mentioned",
    "timeline_story_plan_body": "A plan candidate appeared",
    "timeline_story_promise": "Promise candidate",
    "timeline_story_promise_body": "A promise or commitment candidate appeared",
    "timeline_story_followup": "Follow-up suggested",
    "timeline_story_followup_body": "One open follow-up may need attention",
    "timeline_story_reminder_suggested": "Reminder suggested",
    "timeline_story_reminder_confirmed": "Reminder confirmed",
    "timeline_story_reminder_completed": "Reminder completed",
    "timeline_story_reminder_dismissed": "Reminder dismissed",
    "timeline_story_reminder_body": "Reminder status changed",
    "timeline_story_analysis": "Analysis completed",
    "timeline_story_analysis_body": "{period} overview updated",
    "timeline_story_event": "Timeline event",
    "timeline_story_change_counts": "{current} messages vs {previous} before",
    "timeline_day_part_morning": "Mostly in the morning",
    "timeline_day_part_afternoon": "Mostly in the afternoon",
    "timeline_day_part_evening": "Mostly in the evening",
    "timeline_day_part_night": "Mostly at night",
    "month_title_01": "January",
    "month_title_02": "February",
    "month_title_03": "March",
    "month_title_04": "April",
    "month_title_05": "May",
    "month_title_06": "June",
    "month_title_07": "July",
    "month_title_08": "August",
    "month_title_09": "September",
    "month_title_10": "October",
    "month_title_11": "November",
    "month_title_12": "December",
    "month_day_01": "January",
    "month_day_02": "February",
    "month_day_03": "March",
    "month_day_04": "April",
    "month_day_05": "May",
    "month_day_06": "June",
    "month_day_07": "July",
    "month_day_08": "August",
    "month_day_09": "September",
    "month_day_10": "October",
    "month_day_11": "November",
    "month_day_12": "December",
    "button_compare_periods": "Compare periods",
    "button_previous_period": "Previous period",
    "button_next_period": "Next period",
    "button_back_to_analysis": "Back to analysis",
    "button_not_now": "Not now",
    "ai_verdict_title": "Verdict",
    "ai_direct_findings_title": "Direct findings",
    "verdict_strong": "Strong",
    "verdict_good": "Good",
    "verdict_mixed": "Mixed",
    "verdict_weak": "Weak",
    "verdict_very_weak": "Very weak",
    "verdict_insufficient_data": "Insufficient data",
    "comparison_title": "Compared with the previous period",
    "comparison_not_enough": "Not enough comparable data.",
    "comparison_overall": "Overall",
    "comparison_overall_better": "This conversation was stronger than the previous comparable period.",
    "comparison_overall_worse": "This conversation was weaker than the previous comparable period.",
    "comparison_no_substantial_changes": "No substantial changes.",
    "comparison_metric_message_count": "Message count",
    "comparison_metric_sessions_started_by_you": "Sessions started by you",
    "comparison_metric_sessions_started_by_other": "Sessions started by the other participant",
    "comparison_metric_initiative_balance": "Initiative balance",
    "comparison_metric_response_time": "Response time",
    "comparison_metric_response_consistency": "Response consistency",
    "comparison_metric_average_reply_length": "Average reply length",
    "comparison_metric_question_engagement": "Question engagement",
    "comparison_metric_unanswered_question_rate": "Unanswered-question rate",
    "comparison_metric_topic_continuation": "Topic continuation",
    "comparison_metric_planning_activity": "Planning activity",
    "comparison_metric_follow_up_activity": "Follow-up activity",
    "comparison_metric_sarcasm_intensity": "Sarcasm intensity",
    "comparison_metric_dismissive_low_effort_patterns": "Dismissive or low-effort reply patterns",
    "comparison_metric_pressure_risk": "Pressure risk",
    "comparison_metric_communication_score": "Communication score",
    "comparison_change_sessions_started_by_other_worsened": "The other participant initiated less often",
    "comparison_change_sessions_started_by_other_improved": "The other participant initiated more often",
    "comparison_change_average_reply_length_worsened": "Replies became shorter",
    "comparison_change_average_reply_length_improved": "Replies became longer from a very short baseline",
    "comparison_change_unanswered_question_rate_worsened": "More questions remained unanswered",
    "comparison_change_unanswered_question_rate_improved": "Fewer questions remained unanswered",
    "comparison_change_response_time_stable": "Response speed was almost unchanged",
    "comparison_change_communication_score_worsened": "The communication score decreased",
    "comparison_change_communication_score_improved": "The communication score increased",
    "important_chat_label": "Important chat",
    "important_chats_title": "Important chats",
    "important_mark": "Mark as important",
    "important_remove": "Remove from important",
    "important_empty": "No important chats yet.",
    "automation_analysis": "Automatic analysis",
    "automation_notifications": "Automatic notifications",
    "automation_disable_chat": "Disable for this chat",
    "automation_disable_all": "Disable all automatic analysis",
    "automation_pause_24h": "Pause for 24 hours",
    "conversation_paused_title": "The recent active conversation appears to have paused",
    "conversation_paused_question": "Analyze it?",
    "automation_completed": "Analysis completed automatically",
    "automation_disabled": "Automatic analysis disabled",
    "quiet_hours": "Quiet hours",
    "quiet_start": "Start",
    "quiet_end": "End",
    "minimum_new_messages": "Minimum new messages",
    "inactivity_threshold": "Pause without new messages",
    "automation_mode_local": "Local-only analysis",
    "automation_mode_ai": "AI-enhanced analysis",
    "automation_analysis_mode": "Analysis mode",
    "automation_cooldown": "Cooldown",
    "automation_last": "Last automatic analysis",
    "automation_pending_count": "Pending new-message count",
    "automation_defaults_title": "Automatic analysis defaults",
    "automation_master_switch": "Automatic analysis master switch",
    "automation_suggest": "Suggest first",
    "automation_auto_run": "Run automatically",
    "automation_ai_consent_required": "AI consent is missing or revoked. RelChat will not send messages to OpenAI silently.",
    "report_created": "Created",
    "report_messages": "Messages analyzed",
    "report_confidence": "Confidence",
    "report_completeness": "Completeness",
}
