STRINGS = {
    "app_name": "RelChat",
    "main_title": "RelChat",
    "main_connected": "Telegram connected",
    "main_not_connected": "Telegram not connected",
    "main_saved_chats": "Saved chats",
    "main_reports": "Reports",
    "main_followups": "Follow-ups",
    "main_running": "Analysis running",
    "main_idle": "No analysis running",
    "button_analyze": "Analyze a chat",
    "button_my_chats": "My chats",
    "button_reports": "Reports",
    "button_reminders": "Follow-ups",
    "button_settings": "Settings",
    "button_help": "Help",
    "button_back": "Back",
    "button_cancel": "Cancel",
    "button_main": "Main menu",
    "button_retry": "Retry",
    "button_run_analysis": "Run analysis",
    "button_update_analysis": "Update analysis",
    "button_analyze_again": "Analyze again",
    "button_overview": "Overview",
    "button_insights": "Insights",
    "button_timeline": "Timeline",
    "button_activity": "Activity",
    "button_response": "Response rhythm",
    "button_followups": "Follow-ups",
    "button_habits": "Habits",
    "button_chat_reports": "Reports for this chat",
    "button_chat_reports_short": "Reports",
    "button_chat_settings": "Chat settings",
    "button_delete_local_data": "Delete Local Data",
    "button_chat_home": "Chat Home",
    "button_details": "Details",
    "button_browse_timeline": "Browse timeline",
    "button_timeline_chart": "Activity chart",
    "button_newer": "Newer",
    "button_older": "Older",
    "button_latest_report": "Latest report",
    "button_favorite": "Favorite",
    "button_unfavorite": "Unfavorite",
    "button_rename": "Rename",
    "button_open_chat": "Open chat",
    "button_browse_all": "Browse all chats",
    "button_favorites": "Favorites",
    "button_recently_analyzed": "Recently analyzed",
    "button_saved_chats": "Saved chats",
    "onboarding_1_title": "Welcome to RelChat",
    "onboarding_1_body": "RelChat helps you review selected conversations using local metrics, events, reports, and reminders.",
    "onboarding_2_title": "Privacy model",
    "onboarding_2_body": "Your chat history is read locally through your own Telegram account. The bot itself cannot read private chats through the Bot API.",
    "onboarding_3_connected": "Telegram connected. You can continue to the main menu.",
    "onboarding_3_missing": "Telegram is not connected yet. One local Telegram authorization is required before RelChat can load chats.",
    "onboarding_safe_auth": "Do not send login codes, passwords, API hashes, bot tokens, session files, or phone numbers here.",
    "help_title": "Help",
    "privacy_title": "How privacy works",
    "auth_title": "Why authorization is required",
    "metrics_title": "What metrics mean",
    "limits_title": "What RelChat cannot know",
    "troubleshooting_title": "Troubleshooting",
    "about_title": "About",
    "empty": "Nothing to show yet.",
    "empty_no_analyzed_chats": "No analyzed chats yet. Analyze a chat to create the first Chat Home.",
    "empty_no_recent_chats": "No recently analyzed chats yet.",
    "empty_no_report": "No report exists for this chat yet. Run an analysis to create a snapshot and report.",
    "empty_no_followups": "No follow-ups for this chat yet.",
    "loading_chats": "Loading chats...",
    "loading_chat_home": "Loading chat summary...",
    "loading_failed": "Could not load chats. Check the local Telegram connection and try again.",
    "session_missing": "Telegram is not connected locally yet. Complete the local Telegram authorization first, then return here.",
    "auth_expired": "Telegram authorization appears to have expired. Reconnect locally, then try again.",
    "network_unavailable": "Telegram is unreachable right now. Check the network connection and try again.",
    "flood_wait": "Telegram asked RelChat to wait before continuing. Try again later.",
    "chat_inaccessible": "This chat is not accessible through the connected Telegram account.",
    "expired_navigation": "This screen is no longer available. Return to the main menu and open the chat again.",
    "unknown_action": "That action is no longer available. Return to the main menu.",
    "analysis_already_running": "An analysis is already running for this chat.",
    "no_messages": "No messages were found for the selected period.",
    "invalid_date": "I could not read that date. Try 2026-07-01, 01.07.2026, 7 days, or 30 days.",
    "cancelled": "Analysis cancelled. Imported local messages were kept safely, and no completed report was created.",
    "database_problem": "Local storage had a problem. Try again after checking the local database.",
    "unexpected_error": "Something went wrong. Error reference: {reference}",
    "destructive_note": "This only affects local RelChat data. It never deletes Telegram chats or messages.",
    "chat_type_person": "Person",
    "chat_type_group": "Group",
    "chat_type_channel": "Channel",
    "chat_type_unknown": "Chat",
    "chat_home_current": "Current snapshot",
    "chat_home_changed": "Changed recently",
    "chat_home_attention": "Needs attention",
    "chat_home_explore": "Explore",
    "chat_home_data_quality": "Data quality",
    "chat_home_no_analysis": "No analysis yet.",
    "chat_home_no_analysis_action": "Run an analysis to create a snapshot, report, timeline, and follow-up list.",
    "chat_home_last_period": "Last analyzed period",
    "chat_home_report_freshness": "Report freshness",
    "chat_home_pending_followups": "Pending follow-ups",
    "chat_home_running": "Analysis is currently running for this chat.",
    "chat_home_v4_state_stable": "Everything looks stable.",
    "chat_home_v4_state_group_stable": "Group activity looks stable.",
    "chat_home_v4_state_channel_stable": "Posting activity looks stable.",
    "chat_home_v4_state_attention": "A few items may need your attention.",
    "chat_home_v4_state_long_silence": "No communication for several days.",
    "chat_home_v4_state_group_long_silence": "No group activity for several days.",
    "chat_home_v4_state_channel_long_silence": "No channel posts for several days.",
    "chat_home_v4_state_quiet": "Communication is quieter than the previous period.",
    "chat_home_v4_state_group_quiet": "Group activity is quieter than the previous period.",
    "chat_home_v4_state_channel_quiet": "Posting activity is quieter than the previous period.",
    "chat_home_v4_state_active": "Communication is more active than before.",
    "chat_home_v4_state_group_active": "Group activity is higher than before.",
    "chat_home_v4_state_channel_active": "Posting activity is higher than before.",
    "chat_home_v4_state_no_analysis": "No analysis yet.",
    "chat_home_v4_state_running": "Analysis is running now.",
    "chat_home_v4_last_activity": "Last activity",
    "chat_home_v4_communication_rhythm": "Communication rhythm",
    "chat_home_v4_group_rhythm": "Group activity rhythm",
    "chat_home_v4_posting_cadence": "Posting cadence",
    "chat_home_v4_current_activity": "Current activity",
    "chat_home_v4_current_group_activity": "Current group activity",
    "chat_home_v4_current_posting": "Current posting activity",
    "chat_home_v4_next_reminder": "Next reminder",
    "chat_home_v4_last_analysis": "Last analysis",
    "chat_home_v4_trend": "Trend",
    "chat_home_v4_attention_section": "Attention",
    "chat_home_v4_latest_analysis_section": "Latest analysis",
    "chat_home_v4_latest_analysis_value": "Updated",
    "chat_home_v4_followup_title": "Follow-up",
    "chat_home_v4_followups_count": "{count} follow-ups",
    "chat_home_v4_no_followups_value": "No follow-ups suggested yet.",
    "chat_home_v4_no_reminder_value": "No reminder scheduled.",
    "chat_home_v4_no_analysis_title": "No analysis yet.",
    "chat_home_v4_no_analysis_body": "Run your first analysis to see communication insights.",
    "chat_home_v4_rhythm_regular": "Regular",
    "chat_home_v4_rhythm_bursty": "Bursty",
    "chat_home_v4_rhythm_quiet": "Quiet",
    "chat_home_v4_cadence_regular": "Regular",
    "chat_home_v4_cadence_bursty": "Bursty",
    "chat_home_v4_cadence_quiet": "Quiet",
    "chat_home_v4_unknown": "Not enough data yet",
    "chat_home_v4_activity_up": "Higher than the previous period",
    "chat_home_v4_activity_stable": "Similar to the previous period",
    "chat_home_v4_activity_down": "Lower than the previous period",
    "chat_home_v4_posting_up": "More posts than the previous period",
    "chat_home_v4_posting_stable": "Similar to the previous period",
    "chat_home_v4_posting_down": "Fewer posts than the previous period",
    "chat_home_v4_recent_unknown": "No comparable previous period yet",
    "chat_home_v4_initiation_one_sided": "One participant starts most sessions.",
    "chat_home_v4_initiation_balanced": "Session starts are fairly balanced.",
    "chat_home_v4_group_initiation_balanced": "Several participants start active periods.",
    "chat_home_v4_reply_limited": "Not enough reply data yet.",
    "chat_home_v4_reply_observed": "Replies were observed in this period.",
    "chat_home_v4_not_used_for_channels": "Not used for channels.",
    "chat_home_loading_title": "Loading chat...",
    "chat_home_loading_chat": "Loading chat",
    "chat_home_loading_report": "Loading latest report",
    "chat_home_loading_reminders": "Loading reminders",
    "status_active": "Active",
    "status_quiet": "Quiet",
    "status_attention": "Needs attention",
    "status_long_silence": "Long silence",
    "status_no_analysis": "No analysis",
    "status_loading": "Loading",
    "confidence_high": "High",
    "confidence_medium": "Medium",
    "confidence_low": "Low",
    "chat_settings_title": "Chat settings",
    "chat_settings_body": "These are local RelChat settings for this chat. They do not change Telegram chats or messages.",
    "chat_settings_manage_hint": "Use My chats to rename locally, favorite, or remove local RelChat data.",
    "chat_settings_favorite": "Favorite",
    "yes": "yes",
    "no": "no",
    "relative_today": "Today",
    "relative_yesterday": "Yesterday",
    "relative_tomorrow": "Tomorrow",
    "relative_days_ago": "{count} days ago",
    "relative_in_days": "in {count} days",
    "chat_summary_private": "This summary is based on observable communication patterns only.",
    "chat_summary_group": "This group summary focuses on activity, participation, questions, plans, and follow-ups.",
    "chat_summary_channel": "This channel summary focuses on publishing activity, quiet periods, and content cadence.",
    "chat_summary_messages": "Messages in latest report",
    "chat_changed_unavailable": "Trend comparison is not available yet.",
    "chat_attention_clear": "No follow-ups need attention right now.",
    "chat_attention_questions": "Questions that may need a response",
    "overview_title": "Overview",
    "overview_current_snapshot": "Current snapshot",
    "overview_recent_change": "Recent change",
    "overview_balance": "Balance",
    "overview_response": "Response rhythm",
    "overview_attention": "Needs attention",
    "overview_data_quality": "Data quality",
    "overview_details_title": "Overview details",
    "overview_no_report": "No completed report exists for this chat yet.",
    "overview_no_messages": "There are no analyzed messages in this report.",
    "overview_private_balanced": "Both people contributed at a similar level in this period.",
    "overview_private_one_sided_initiation": "The conversation has replies when active, while one participant starts most sessions.",
    "overview_private_active": "The conversation has enough activity to summarize observable communication patterns.",
    "overview_group": "This group was active enough to summarize participation, questions, plans, and follow-ups.",
    "overview_channel": "This channel overview focuses on posting activity and content cadence, not replies.",
    "overview_limited_sample": "The sample is limited, so RelChat avoids percentage-based conclusions.",
    "overview_recent_missing": "No comparable previous period is available yet.",
    "overview_recent_limited": "A previous report exists, but there is not enough comparable data to describe a change.",
    "overview_recent_similar": "Activity looks similar to the previous comparable period.",
    "overview_recent_higher": "Activity is higher than the previous comparable period.",
    "overview_recent_lower": "Activity is lower than the previous comparable period.",
    "overview_initiation_split": "Session starts",
    "overview_reply_participation": "Reply participation",
    "overview_planning_balance_unavailable": "Planning and follow-up participation by person is not available in this report.",
    "overview_typical_response": "Typical response time",
    "overview_active_response": "Active-chat response time",
    "overview_consistency": "Consistency",
    "overview_consistent": "Response rhythm looks fairly consistent in this period.",
    "overview_varied": "Response rhythm varies noticeably in this period.",
    "overview_response_limited": "There is not enough alternating-message data to summarize response rhythm.",
    "overview_no_attention": "No unresolved questions, plans, promises, or confirmed reminders need attention right now.",
    "overview_unanswered_questions": "Unanswered questions",
    "overview_unresolved_plans": "Plans to review",
    "overview_promises_followups": "Promises and follow-ups",
    "overview_confirmed_reminders": "Confirmed reminders",
    "overview_long_silences": "Quiet periods",
    "overview_average_length": "Average message length",
    "overview_imported_range": "Imported range",
    "overview_limitations": "Limitations",
    "overview_not_enough_for_percent": "Counts are shown without percentages because the sample is small.",
    "overview_count": "count",
    "not_available": "not available",
    "button_full_analysis": "Full analysis",
    "button_ai_analysis": "AI-enhanced analysis",
    "button_local_analysis": "Local analysis",
    "button_continue_ai": "Continue with AI",
    "button_use_local_analysis": "Use local analysis",
    "button_revoke_ai_consent": "Revoke AI consent",
    "button_result_details": "Details",
    "analysis_result_title": "Analysis complete",
    "analysis_result_local_mode": "Local analysis",
    "analysis_result_period": "Period",
    "analysis_result_messages": "Messages analyzed",
    "analysis_result_stands_out": "What stands out",
    "analysis_result_attention": "Needs attention",
    "analysis_result_quality": "Data quality",
    "analysis_result_ai_partial": "AI-enhanced analysis was unavailable, so this result uses local analysis.",
    "analysis_mode_title": "Choose analysis type",
    "analysis_mode_body": "Local analysis stays on this machine. AI-enhanced analysis can add a communication-style summary after you consent.",
    "ai_consent_prompt": "AI-enhanced analysis sends the selected conversation messages to OpenAI.\nYou can continue with local-only analysis instead.",
    "ai_error_disabled": "AI-enhanced analysis is currently disabled.",
    "ai_error_missing_key": "AI-enhanced analysis is not configured because the OpenAI API key is missing.",
    "ai_error_missing_model": "AI-enhanced analysis is not configured because the model name is missing.",
    "ai_error_sdk_missing": "AI-enhanced analysis needs the optional OpenAI Python SDK.",
    "ai_error_generic": "AI-enhanced analysis is unavailable right now.",
    "ai_error_failed": "AI-enhanced analysis failed safely. Local analysis is still available.",
    "ai_offer_local": "You can continue with local-only analysis instead.",
    "ai_communication_analysis": "Communication analysis",
    "ai_activity_analysis": "Activity analysis",
    "ai_communication_score": "Communication score",
    "ai_activity_score": "Activity score",
    "ai_confidence_line": "Confidence: {confidence}",
    "ai_summary_title": "Summary",
    "ai_strengths_title": "Strong sides",
    "ai_weakens_title": "What weakens it",
    "ai_main_advice": "Main advice",
    "ai_advice_title": "Advice",
    "ai_weak_replies_title": "Replies that weakened the conversation",
    "ai_scores_title": "Scores",
    "ai_example": "Example",
    "ai_no_raw_text_note": "Raw message text is hidden by default.",
    "ai_no_weak_replies": "No weakened-reply patterns were found in this result.",
    "ai_severity": "Severity",
    "ai_reference": "Reference",
    "ai_score_formula": "Overall score = weighted positive communication dimensions minus risk penalties, clamped to 0-10.",
    "ai_limitations_title": "Limitations",
    "ai_full_analysis_title": "Full analysis",
    "ai_you_title": "How you communicate",
    "ai_other_title": "How the other person communicates",
    "ai_consent_status": "AI consent",
    "settings_ai_consent_active": "active",
    "settings_ai_consent_not_active": "not active",
    "ai_consent_revoked": "AI consent was revoked. Future AI-enhanced analyses will ask again before sending selected messages to OpenAI.",
    "ai_dimension_reciprocity": "Reciprocity",
    "ai_dimension_initiative_balance": "Initiative",
    "ai_dimension_reply_quality": "Reply quality",
    "ai_dimension_respectfulness": "Respectfulness",
    "ai_dimension_topic_continuation": "Topic continuation",
    "ai_dimension_support_attention": "Support and attention",
    "ai_dimension_planning_cooperation": "Planning cooperation",
    "ai_dimension_pressure_risk": "Pressure risk",
    "ai_dimension_hostility": "Hostility",
    "ai_dimension_dismissiveness": "Dismissiveness",
    "ai_dimension_unresolved_question_rate": "Unresolved questions",
    "ai_dimension_sarcasm_intensity": "Sarcasm intensity",
    "ai_weak_ignored_question": "Direct question ignored",
    "ai_weak_abrupt_reply": "Abrupt reply",
    "ai_weak_sarcasm": "Sarcasm replacing a direct answer",
    "ai_weak_dismissive": "Dismissive wording",
    "ai_weak_topic_switch": "Abrupt topic change",
    "ai_weak_low_effort": "Low-effort reply",
    "ai_weak_hostile": "Hostile wording",
    "ai_weak_pressure": "Response that increases pressure",
    "chat_home_details_title": "Details",
    "chat_home_details_body": "Open the full analysis, timeline, activity, follow-ups, previous analyses, or local chat settings.",
    "response_bucket_minutes": "within a few minutes",
    "response_bucket_hour": "within about an hour",
    "response_bucket_hours": "within a few hours",
    "response_bucket_day": "within the same day",
    "response_bucket_over_day": "over a day",
    "chat_reports_title": "Reports for this chat",
    "my_chats_title": "My chats",
    "my_chats_choose": "Choose a chat.",
    "my_chats_choose_section": "Choose a section.",
    "my_chats_favorites": "Favorites",
    "my_chats_recent": "Recently analyzed",
    "my_chats_saved": "Saved chats",
    "module_coming_soon": "Coming soon",
    "module_experimental": "Experimental",
    "module_not_included": "Not included in this report",
    "section_timeline_title": "Timeline",
    "section_activity_title": "Activity",
    "section_response_title": "Response rhythm",
    "section_followups_title": "Follow-ups",
    "section_habits_title": "Habits",
    "section_reports_title": "Reports",
    "section_unavailable_body": "This screen is prepared for Product UX v3, but this calculation is not available in the selected report.",
    "section_coming_soon_body": "This section is prepared for a future release and does not show generated results yet.",
    "section_channel_hidden_body": "This section is hidden for channels because reply rhythm and initiation balance are not meaningful without imported replies.",
    "selected_prefix": "Selected:",
    "timeline_private_note": "Shows observable communication rhythm between two participants. It does not infer feelings or intentions.",
    "timeline_group_note": "Shows group activity, quiet periods, questions, plans, and follow-ups without relationship wording.",
    "timeline_channel_note": "Shows publishing activity and quiet periods. Reply balance and initiation are hidden for channels.",
    "timeline_empty": "No timeline data is available yet. Run an analysis after importing messages to create activity periods and event markers.",
    "timeline_privacy_note": "No raw message text is shown in timeline entries.",
    "timeline_analyzed_period": "Analyzed period",
    "timeline_most_active": "Most active period",
    "timeline_longest_silence": "Longest silence",
    "timeline_meaningful_events": "Meaningful events",
    "timeline_recent_change": "Recent change",
    "timeline_recent_higher": "Activity increased compared with the previous active period.",
    "timeline_recent_lower": "Activity decreased compared with the previous active period.",
    "timeline_recent_similar": "Activity looks similar to the previous active period.",
    "timeline_recent_limited": "Recent change needs more messages before comparing.",
    "timeline_recent_unavailable": "Not enough timeline history to compare yet.",
    "timeline_filter": "Filter",
    "timeline_filter_all": "All",
    "timeline_filter_activity": "Activity",
    "timeline_filter_questions": "Questions",
    "timeline_filter_plans": "Plans",
    "timeline_filter_followups": "Follow-ups",
    "timeline_filter_silences": "Silences",
    "timeline_empty_filter": "No timeline entries match this filter yet.",
    "timeline_no_entries": "No entries",
    "timeline_showing": "Showing",
    "timeline_event_activity": "Activity period",
    "timeline_event_quiet": "Quiet period",
    "timeline_event_silence": "Long silence",
    "timeline_event_question": "Question detected",
    "timeline_event_unanswered": "Question may need a response",
    "timeline_event_plan": "Plan candidate",
    "timeline_event_promise": "Promise candidate",
    "timeline_event_followup": "Follow-up candidate",
    "timeline_event_reminder": "Confirmed reminder",
    "timeline_event_analysis": "Analysis completed",
    "timeline_sender": "Sender",
    "timeline_participant": "Participant",
    "timeline_member": "Member",
    "timeline_period": "Period",
    "timeline_gap": "Gap",
    "timeline_report_period": "Report period",
    "timeline_source_message": "Message marker",
    "timeline_rule_source": "Detected by",
    "timeline_chart_caption": "RelChat activity chart. No message text is included.",
    "timeline_chart_failed": "Could not create the activity chart right now. The text timeline is still available.",
    "timeline_empty_story": "No timeline story is available yet. Run an analysis after importing messages to see how activity changed over time.",
    "timeline_story_conversation_active": "Conversation active",
    "timeline_story_group_active": "Group active",
    "timeline_story_channel_active": "Channel active",
    "timeline_story_activity_body": "{messages} across {periods}",
    "timeline_story_activity_channel_body": "{posts} across {periods}",
    "timeline_count_message_one": "1 message",
    "timeline_count_message_many": "{count} messages",
    "timeline_count_post_one": "1 post",
    "timeline_count_post_many": "{count} posts",
    "timeline_count_period_one": "1 active period",
    "timeline_count_period_many": "{count} active periods",
    "timeline_story_resumed": "Conversation resumed",
    "timeline_story_resumed_body": "Activity returned after {days} quiet days",
    "timeline_story_quiet_period": "Long quiet period",
    "timeline_story_quiet_body": "No visible messages for {days} days",
    "timeline_story_activity_increased": "Activity increased",
    "timeline_story_activity_increased_body": "More active than the previous comparable period",
    "timeline_story_activity_decreased": "Activity decreased",
    "timeline_story_activity_decreased_body": "Quieter than the previous comparable period",
    "timeline_story_question": "Question detected",
    "timeline_story_question_body": "A question appeared in the conversation",
    "timeline_story_unanswered_question": "Question may need a response",
    "timeline_story_unanswered_question_body": "One open question may need attention",
    "timeline_story_plan": "Plan mentioned",
    "timeline_story_plan_body": "A plan candidate appeared",
    "timeline_story_promise": "Promise candidate",
    "timeline_story_promise_body": "A promise or commitment candidate appeared",
    "timeline_story_followup": "Follow-up suggested",
    "timeline_story_followup_body": "One open follow-up may need attention",
    "timeline_story_reminder_suggested": "Reminder suggested",
    "timeline_story_reminder_confirmed": "Reminder confirmed",
    "timeline_story_reminder_completed": "Reminder completed",
    "timeline_story_reminder_dismissed": "Reminder dismissed",
    "timeline_story_reminder_body": "Reminder status changed",
    "timeline_story_analysis": "Analysis completed",
    "timeline_story_analysis_body": "{period} overview updated",
    "timeline_story_event": "Timeline event",
    "timeline_story_change_counts": "{current} messages vs {previous} before",
    "timeline_day_part_morning": "Mostly in the morning",
    "timeline_day_part_afternoon": "Mostly in the afternoon",
    "timeline_day_part_evening": "Mostly in the evening",
    "timeline_day_part_night": "Mostly at night",
    "month_title_01": "January",
    "month_title_02": "February",
    "month_title_03": "March",
    "month_title_04": "April",
    "month_title_05": "May",
    "month_title_06": "June",
    "month_title_07": "July",
    "month_title_08": "August",
    "month_title_09": "September",
    "month_title_10": "October",
    "month_title_11": "November",
    "month_title_12": "December",
    "month_day_01": "January",
    "month_day_02": "February",
    "month_day_03": "March",
    "month_day_04": "April",
    "month_day_05": "May",
    "month_day_06": "June",
    "month_day_07": "July",
    "month_day_08": "August",
    "month_day_09": "September",
    "month_day_10": "October",
    "month_day_11": "November",
    "month_day_12": "December",
    "report_created": "Created",
    "report_messages": "Messages analyzed",
    "report_confidence": "Confidence",
    "report_completeness": "Completeness",
}
