STRINGS = {
    "app_name": "RelChat",
    "main_title": "RelChat",
    "main_connected": "Telegram подключен",
    "main_not_connected": "Telegram не подключен",
    "main_saved_chats": "Сохраненные чаты",
    "main_reports": "Отчеты",
    "main_followups": "Напоминания",
    "main_running": "Анализ выполняется",
    "main_idle": "Анализ не выполняется",
    "button_analyze": "Проанализировать чат",
    "button_my_chats": "Мои чаты",
    "button_reports": "Отчеты",
    "button_reminders": "Напоминания",
    "button_settings": "Настройки",
    "button_help": "Помощь",
    "button_back": "Назад",
    "button_cancel": "Отмена",
    "button_main": "Главное меню",
    "button_retry": "Повторить",
    "button_run_analysis": "Запустить анализ",
    "button_update_analysis": "Обновить анализ",
    "button_analyze_again": "Проанализировать снова",
    "button_overview": "Обзор",
    "button_insights": "Инсайты",
    "button_timeline": "Хронология",
    "button_activity": "Активность",
    "button_response": "Ритм ответов",
    "button_followups": "Напоминания",
    "button_habits": "Привычки",
    "button_chat_reports": "Отчеты по этому чату",
    "button_chat_reports_short": "Отчеты",
    "button_chat_settings": "Настройки чата",
    "button_delete_local_data": "Удалить локальные данные",
    "button_chat_home": "Экран чата",
    "button_details": "Детали",
    "button_browse_timeline": "Открыть хронологию",
    "button_timeline_chart": "График активности",
    "button_newer": "Новее",
    "button_older": "Старее",
    "button_latest_report": "Последний отчет",
    "button_favorite": "В избранное",
    "button_unfavorite": "Убрать из избранного",
    "button_rename": "Переименовать",
    "button_open_chat": "Открыть чат",
    "button_browse_all": "Все чаты",
    "button_favorites": "Избранное",
    "button_recently_analyzed": "Недавно анализировали",
    "button_saved_chats": "Сохраненные чаты",
    "onboarding_1_title": "Добро пожаловать в RelChat",
    "onboarding_1_body": "RelChat помогает просматривать выбранные переписки через локальные метрики, события, отчеты и напоминания.",
    "onboarding_2_title": "Приватность",
    "onboarding_2_body": "История чатов читается локально через ваш собственный аккаунт Telegram. Сам бот не может читать приватные чаты через Bot API.",
    "onboarding_3_connected": "Telegram подключен. Можно перейти в главное меню.",
    "onboarding_3_missing": "Telegram пока не подключен. Перед загрузкой чатов нужна одна локальная авторизация Telegram.",
    "onboarding_safe_auth": "Не отправляйте сюда коды входа, пароли, API hash, токены бота, файлы сессии или номер телефона.",
    "help_title": "Помощь",
    "privacy_title": "Как работает приватность",
    "auth_title": "Зачем нужна авторизация",
    "metrics_title": "Что означают метрики",
    "limits_title": "Чего RelChat не может знать",
    "troubleshooting_title": "Решение проблем",
    "about_title": "О проекте",
    "empty": "Пока ничего нет.",
    "empty_no_analyzed_chats": "Пока нет проанализированных чатов. Проанализируйте чат, чтобы создать первый экран чата.",
    "empty_no_recent_chats": "Пока нет недавно проанализированных чатов.",
    "empty_no_report": "Для этого чата пока нет отчета. Запустите анализ, чтобы создать обзор и отчет.",
    "empty_no_followups": "Для этого чата пока нет напоминаний.",
    "loading_chats": "Загружаю чаты...",
    "loading_chat_home": "Загружаю сводку чата...",
    "loading_failed": "Не удалось загрузить чаты. Проверьте локальное подключение Telegram и попробуйте снова.",
    "session_missing": "Telegram пока не подключен локально. Завершите локальную авторизацию Telegram и вернитесь сюда.",
    "auth_expired": "Похоже, авторизация Telegram истекла. Подключите аккаунт локально и попробуйте снова.",
    "network_unavailable": "Telegram сейчас недоступен. Проверьте сеть и попробуйте снова.",
    "flood_wait": "Telegram попросил RelChat подождать. Попробуйте позже.",
    "chat_inaccessible": "Этот чат недоступен через подключенный аккаунт Telegram.",
    "expired_navigation": "Этот экран больше недоступен. Вернитесь в главное меню и откройте чат снова.",
    "unknown_action": "Это действие больше недоступно. Вернитесь в главное меню.",
    "analysis_already_running": "Для этого чата уже выполняется анализ.",
    "no_messages": "За выбранный период сообщений не найдено.",
    "invalid_date": "Не удалось распознать дату. Попробуйте 2026-07-01, 01.07.2026, 7 days или 30 days.",
    "cancelled": "Анализ отменен. Уже импортированные локальные сообщения сохранены, завершенный отчет не создан.",
    "database_problem": "Возникла проблема с локальным хранилищем. Проверьте локальную базу данных и попробуйте снова.",
    "unexpected_error": "Что-то пошло не так. Код ошибки: {reference}",
    "destructive_note": "Это влияет только на локальные данные RelChat. Чаты и сообщения в Telegram не удаляются.",
    "chat_type_person": "Человек",
    "chat_type_group": "Группа",
    "chat_type_channel": "Канал",
    "chat_type_unknown": "Чат",
    "chat_home_current": "Текущий обзор",
    "chat_home_changed": "Что изменилось",
    "chat_home_attention": "Требует внимания",
    "chat_home_explore": "Разделы",
    "chat_home_data_quality": "Качество данных",
    "chat_home_no_analysis": "Анализа пока нет.",
    "chat_home_no_analysis_action": "Запустите анализ, чтобы создать обзор, отчет, хронологию и список напоминаний.",
    "chat_home_last_period": "Последний период анализа",
    "chat_home_report_freshness": "Актуальность отчета",
    "chat_home_pending_followups": "Активные напоминания",
    "chat_home_running": "Для этого чата сейчас выполняется анализ.",
    "chat_home_v4_state_stable": "Все выглядит стабильно.",
    "chat_home_v4_state_group_stable": "Активность группы выглядит стабильной.",
    "chat_home_v4_state_channel_stable": "Публикации выглядят стабильными.",
    "chat_home_v4_state_attention": "Есть несколько пунктов, которые стоит проверить.",
    "chat_home_v4_state_long_silence": "Несколько дней не было общения.",
    "chat_home_v4_state_group_long_silence": "Несколько дней не было активности в группе.",
    "chat_home_v4_state_channel_long_silence": "Несколько дней не было публикаций в канале.",
    "chat_home_v4_state_quiet": "Общение стало тише, чем в предыдущий период.",
    "chat_home_v4_state_group_quiet": "Активность группы ниже, чем в предыдущий период.",
    "chat_home_v4_state_channel_quiet": "Публикаций меньше, чем в предыдущий период.",
    "chat_home_v4_state_active": "Общение стало активнее, чем раньше.",
    "chat_home_v4_state_group_active": "Активность группы выше, чем раньше.",
    "chat_home_v4_state_channel_active": "Публикаций стало больше, чем раньше.",
    "chat_home_v4_state_no_analysis": "Анализа пока нет.",
    "chat_home_v4_state_running": "Анализ сейчас выполняется.",
    "chat_home_v4_last_activity": "Последняя активность",
    "chat_home_v4_communication_rhythm": "Ритм общения",
    "chat_home_v4_group_rhythm": "Ритм активности группы",
    "chat_home_v4_posting_cadence": "Ритм публикаций",
    "chat_home_v4_current_activity": "Текущая активность",
    "chat_home_v4_current_group_activity": "Текущая активность группы",
    "chat_home_v4_current_posting": "Текущая активность публикаций",
    "chat_home_v4_next_reminder": "Следующее напоминание",
    "chat_home_v4_last_analysis": "Последний анализ",
    "chat_home_v4_trend": "Тренд",
    "chat_home_v4_attention_section": "Внимание",
    "chat_home_v4_latest_analysis_section": "Последний анализ",
    "chat_home_v4_latest_analysis_value": "Обновлено",
    "chat_home_v4_followup_title": "Напоминания",
    "chat_home_v4_followups_count": "Напоминаний: {count}",
    "chat_home_v4_no_followups_value": "Пока нет предложенных напоминаний.",
    "chat_home_v4_no_reminder_value": "Напоминание не запланировано.",
    "chat_home_v4_no_analysis_title": "Анализа пока нет.",
    "chat_home_v4_no_analysis_body": "Запустите первый анализ, чтобы увидеть инсайты по общению.",
    "chat_home_v4_rhythm_regular": "Регулярный",
    "chat_home_v4_rhythm_bursty": "Всплесками",
    "chat_home_v4_rhythm_quiet": "Тихий",
    "chat_home_v4_cadence_regular": "Регулярный",
    "chat_home_v4_cadence_bursty": "Всплесками",
    "chat_home_v4_cadence_quiet": "Тихий",
    "chat_home_v4_unknown": "Пока недостаточно данных",
    "chat_home_v4_activity_up": "Выше, чем в предыдущий период",
    "chat_home_v4_activity_stable": "Похоже на предыдущий период",
    "chat_home_v4_activity_down": "Ниже, чем в предыдущий период",
    "chat_home_v4_posting_up": "Публикаций больше, чем в предыдущий период",
    "chat_home_v4_posting_stable": "Похоже на предыдущий период",
    "chat_home_v4_posting_down": "Публикаций меньше, чем в предыдущий период",
    "chat_home_v4_recent_unknown": "Пока нет сопоставимого предыдущего периода",
    "chat_home_v4_initiation_one_sided": "Большинство сессий начинает один участник.",
    "chat_home_v4_initiation_balanced": "Начало сессий распределено достаточно ровно.",
    "chat_home_v4_group_initiation_balanced": "Активные периоды начинают разные участники.",
    "chat_home_v4_reply_limited": "Пока недостаточно данных об ответах.",
    "chat_home_v4_reply_observed": "В этот период были ответы.",
    "chat_home_v4_not_used_for_channels": "Не используется для каналов.",
    "chat_home_loading_title": "Загружаю чат...",
    "chat_home_loading_chat": "Загружаю чат",
    "chat_home_loading_report": "Загружаю последний отчет",
    "chat_home_loading_reminders": "Загружаю напоминания",
    "status_active": "Активно",
    "status_quiet": "Тихо",
    "status_attention": "Требует внимания",
    "status_long_silence": "Долгая пауза",
    "status_no_analysis": "Нет анализа",
    "status_loading": "Загрузка",
    "confidence_high": "Высокая",
    "confidence_medium": "Средняя",
    "confidence_low": "Низкая",
    "chat_settings_title": "Настройки чата",
    "chat_settings_body": "Это локальные настройки RelChat для этого чата. Они не меняют чаты или сообщения в Telegram.",
    "chat_settings_manage_hint": "В разделе Мои чаты можно переименовать локально, добавить в избранное или удалить локальные данные RelChat.",
    "chat_settings_favorite": "Избранное",
    "yes": "да",
    "no": "нет",
    "relative_today": "Сегодня",
    "relative_yesterday": "Вчера",
    "relative_tomorrow": "Завтра",
    "relative_days_ago": "{count} дн. назад",
    "relative_in_days": "через {count} дн.",
    "chat_summary_private": "Сводка основана только на наблюдаемых паттернах общения.",
    "chat_summary_group": "Сводка группы показывает активность, участие, вопросы, планы и напоминания.",
    "chat_summary_channel": "Сводка канала показывает публикации, тихие периоды и ритм контента.",
    "chat_summary_messages": "Сообщений в последнем отчете",
    "chat_changed_unavailable": "Сравнение трендов пока недоступно.",
    "chat_attention_clear": "Сейчас нет напоминаний, требующих внимания.",
    "chat_attention_questions": "Вопросы, которые могут требовать ответа",
    "overview_title": "Обзор",
    "overview_current_snapshot": "Текущий обзор",
    "overview_recent_change": "Недавнее изменение",
    "overview_balance": "Баланс",
    "overview_response": "Ритм ответов",
    "overview_attention": "Требует внимания",
    "overview_data_quality": "Качество данных",
    "overview_details_title": "Детали обзора",
    "overview_no_report": "Для этого чата пока нет завершенного отчета.",
    "overview_no_messages": "В этом отчете нет проанализированных сообщений.",
    "overview_private_balanced": "В этот период оба участника общались примерно на сопоставимом уровне.",
    "overview_private_one_sided_initiation": "Когда разговор активен, ответы есть, но большинство сессий начинает один участник.",
    "overview_private_active": "Активности достаточно, чтобы кратко описать наблюдаемые паттерны общения.",
    "overview_group": "В группе достаточно активности, чтобы кратко описать участие, вопросы, планы и напоминания.",
    "overview_channel": "Обзор канала показывает публикации и ритм контента, а не ответы.",
    "overview_limited_sample": "Выборка ограничена, поэтому RelChat не делает выводы с процентами.",
    "overview_recent_missing": "Пока нет сопоставимого предыдущего периода.",
    "overview_recent_limited": "Предыдущий отчет есть, но данных недостаточно для корректного сравнения.",
    "overview_recent_similar": "Активность похожа на предыдущий сопоставимый период.",
    "overview_recent_higher": "Активность выше, чем в предыдущем сопоставимом периоде.",
    "overview_recent_lower": "Активность ниже, чем в предыдущем сопоставимом периоде.",
    "overview_initiation_split": "Начало сессий",
    "overview_reply_participation": "Участие в ответах",
    "overview_planning_balance_unavailable": "Баланс планов и напоминаний по участникам недоступен в этом отчете.",
    "overview_typical_response": "Обычное время ответа",
    "overview_active_response": "Ответы в активном чате",
    "overview_consistency": "Стабильность",
    "overview_consistent": "Ритм ответов в этот период выглядит достаточно стабильным.",
    "overview_varied": "Ритм ответов в этот период заметно меняется.",
    "overview_response_limited": "Недостаточно чередующихся сообщений, чтобы описать ритм ответов.",
    "overview_no_attention": "Сейчас нет нерешенных вопросов, планов, обещаний или подтвержденных напоминаний.",
    "overview_unanswered_questions": "Вопросы без ответа",
    "overview_unresolved_plans": "Планы для проверки",
    "overview_promises_followups": "Обещания и напоминания",
    "overview_confirmed_reminders": "Подтвержденные напоминания",
    "overview_long_silences": "Тихие периоды",
    "overview_average_length": "Средняя длина сообщения",
    "overview_imported_range": "Загруженный диапазон",
    "overview_limitations": "Ограничения",
    "overview_not_enough_for_percent": "Проценты не показаны, потому что выборка мала.",
    "overview_count": "количество",
    "not_available": "недоступно",
    "button_full_analysis": "Полный анализ",
    "button_ai_analysis": "Расширенный ИИ-анализ",
    "button_local_analysis": "Локальный анализ",
    "button_continue_ai": "Продолжить с ИИ",
    "button_use_local_analysis": "Использовать локальный анализ",
    "button_revoke_ai_consent": "Отозвать согласие на ИИ",
    "analysis_mode_title": "Выберите тип анализа",
    "analysis_mode_body": "Локальный анализ остается на этом устройстве. Расширенный ИИ-анализ может добавить сводку по стилю общения после вашего согласия.",
    "ai_consent_prompt": "Расширенный ИИ-анализ отправляет выбранные сообщения переписки в OpenAI.\nВместо этого можно использовать только локальный анализ.",
    "ai_error_disabled": "Расширенный ИИ-анализ сейчас отключен.",
    "ai_error_missing_key": "Расширенный ИИ-анализ не настроен: отсутствует OpenAI API key.",
    "ai_error_missing_model": "Расширенный ИИ-анализ не настроен: отсутствует название модели.",
    "ai_error_sdk_missing": "Для расширенного ИИ-анализа нужен опциональный Python SDK OpenAI.",
    "ai_error_generic": "Расширенный ИИ-анализ сейчас недоступен.",
    "ai_error_failed": "Расширенный ИИ-анализ завершился безопасной ошибкой. Локальный анализ доступен.",
    "ai_offer_local": "Вместо этого можно использовать только локальный анализ.",
    "ai_communication_analysis": "Анализ общения",
    "ai_activity_analysis": "Анализ активности",
    "ai_communication_score": "Общая оценка",
    "ai_activity_score": "Оценка активности",
    "ai_confidence_line": "Уверенность: {confidence}",
    "ai_summary_title": "Краткий вывод",
    "ai_strengths_title": "Сильные стороны",
    "ai_weakens_title": "Что мешает диалогу",
    "ai_main_advice": "Главный совет",
    "ai_advice_title": "Советы",
    "ai_weak_replies_title": "Ответы, которые мешали диалогу",
    "ai_scores_title": "Оценки",
    "ai_example": "Пример",
    "ai_no_raw_text_note": "Текст сообщений по умолчанию скрыт.",
    "ai_no_weak_replies": "В этом результате не найдено паттернов, которые заметно мешали диалогу.",
    "ai_severity": "Серьезность",
    "ai_reference": "Ссылка",
    "ai_score_formula": "Общая оценка = взвешенные позитивные измерения общения минус штрафы риска, в диапазоне 0-10.",
    "ai_limitations_title": "Ограничения",
    "ai_full_analysis_title": "Полный анализ",
    "ai_you_title": "Как вы ведете переписку",
    "ai_other_title": "Как собеседник ведет переписку",
    "ai_consent_status": "Согласие на ИИ",
    "settings_ai_consent_active": "активно",
    "settings_ai_consent_not_active": "не активно",
    "ai_consent_revoked": "Согласие на ИИ отозвано. При следующем расширенном ИИ-анализе RelChat снова спросит разрешение перед отправкой выбранных сообщений в OpenAI.",
    "ai_dimension_reciprocity": "Взаимность",
    "ai_dimension_initiative_balance": "Инициатива",
    "ai_dimension_reply_quality": "Качество ответов",
    "ai_dimension_respectfulness": "Уважительность",
    "ai_dimension_topic_continuation": "Продолжение тем",
    "ai_dimension_support_attention": "Поддержка и внимание",
    "ai_dimension_planning_cooperation": "Согласование планов",
    "ai_dimension_pressure_risk": "Риск давления",
    "ai_dimension_hostility": "Враждебность",
    "ai_dimension_dismissiveness": "Обесценивание",
    "ai_dimension_unresolved_question_rate": "Нерешенные вопросы",
    "ai_dimension_sarcasm_intensity": "Выраженность сарказма",
    "ai_weak_ignored_question": "Прямой вопрос остался без ответа",
    "ai_weak_abrupt_reply": "Резкий ответ",
    "ai_weak_sarcasm": "Сарказм вместо прямого ответа",
    "ai_weak_dismissive": "Обесценивающая формулировка",
    "ai_weak_topic_switch": "Резкая смена темы",
    "ai_weak_low_effort": "Слишком короткий ответ",
    "ai_weak_hostile": "Враждебная формулировка",
    "ai_weak_pressure": "Ответ усиливает давление",
    "chat_home_details_title": "Детали",
    "chat_home_details_body": "Откройте полный анализ, хронологию, активность, напоминания, предыдущие анализы или локальные настройки чата.",
    "response_bucket_minutes": "в течение нескольких минут",
    "response_bucket_hour": "примерно в течение часа",
    "response_bucket_hours": "в течение нескольких часов",
    "response_bucket_day": "в течение того же дня",
    "response_bucket_over_day": "больше дня",
    "chat_reports_title": "Отчеты по этому чату",
    "my_chats_title": "Мои чаты",
    "my_chats_choose": "Выберите чат.",
    "my_chats_choose_section": "Выберите раздел.",
    "my_chats_favorites": "Избранное",
    "my_chats_recent": "Недавно анализировали",
    "my_chats_saved": "Сохраненные чаты",
    "module_coming_soon": "Скоро",
    "module_experimental": "Экспериментально",
    "module_not_included": "Не включено в этот отчет",
    "section_timeline_title": "Хронология",
    "section_activity_title": "Активность",
    "section_response_title": "Ритм ответов",
    "section_followups_title": "Напоминания",
    "section_habits_title": "Привычки",
    "section_reports_title": "Отчеты",
    "section_unavailable_body": "Этот экран подготовлен для Product UX v3, но расчет не включен в выбранный отчет.",
    "section_coming_soon_body": "Этот раздел подготовлен для будущего релиза и пока не показывает сгенерированные результаты.",
    "section_channel_hidden_body": "Этот раздел скрыт для каналов: ритм ответов и начало сессий не имеют смысла без импортированных ответов.",
    "selected_prefix": "Выбрано:",
    "timeline_private_note": "Показывает наблюдаемый ритм общения между двумя участниками. RelChat не делает выводов о чувствах или намерениях.",
    "timeline_group_note": "Показывает активность группы, тихие периоды, вопросы, планы и напоминания без формулировок про отношения.",
    "timeline_channel_note": "Показывает публикации и тихие периоды. Баланс ответов и начало сессий скрыты для каналов.",
    "timeline_empty": "Данных для хронологии пока нет. Запустите анализ после импорта сообщений, чтобы создать периоды активности и отметки событий.",
    "timeline_privacy_note": "Текст сообщений в хронологии не показывается.",
    "timeline_analyzed_period": "Период анализа",
    "timeline_most_active": "Самый активный период",
    "timeline_longest_silence": "Самая длинная пауза",
    "timeline_meaningful_events": "Значимые события",
    "timeline_recent_change": "Недавнее изменение",
    "timeline_recent_higher": "Активность выросла по сравнению с предыдущим активным периодом.",
    "timeline_recent_lower": "Активность снизилась по сравнению с предыдущим активным периодом.",
    "timeline_recent_similar": "Активность похожа на предыдущий активный период.",
    "timeline_recent_limited": "Для сравнения недавних изменений нужно больше сообщений.",
    "timeline_recent_unavailable": "Пока недостаточно истории для сравнения.",
    "timeline_filter": "Фильтр",
    "timeline_filter_all": "Все",
    "timeline_filter_activity": "Активность",
    "timeline_filter_questions": "Вопросы",
    "timeline_filter_plans": "Планы",
    "timeline_filter_followups": "Напоминания",
    "timeline_filter_silences": "Паузы",
    "timeline_empty_filter": "Для этого фильтра пока нет записей хронологии.",
    "timeline_no_entries": "Нет записей",
    "timeline_showing": "Показано",
    "timeline_event_activity": "Период активности",
    "timeline_event_quiet": "Тихий период",
    "timeline_event_silence": "Долгая пауза",
    "timeline_event_question": "Найден вопрос",
    "timeline_event_unanswered": "Вопрос может требовать ответа",
    "timeline_event_plan": "Возможный план",
    "timeline_event_promise": "Возможное обещание",
    "timeline_event_followup": "Кандидат для напоминания",
    "timeline_event_reminder": "Подтвержденное напоминание",
    "timeline_event_analysis": "Анализ завершен",
    "timeline_sender": "Отправитель",
    "timeline_participant": "Участник",
    "timeline_member": "Участник",
    "timeline_period": "Период",
    "timeline_gap": "Пауза",
    "timeline_report_period": "Период отчета",
    "timeline_source_message": "Метка сообщения",
    "timeline_rule_source": "Правило",
    "timeline_chart_caption": "График активности RelChat. Текст сообщений не включен.",
    "timeline_chart_failed": "Не удалось создать график активности сейчас. Текстовая хронология по-прежнему доступна.",
    "timeline_empty_story": "Истории хронологии пока нет. Запустите анализ после импорта сообщений, чтобы увидеть, как менялась активность.",
    "timeline_story_conversation_active": "Разговор активен",
    "timeline_story_group_active": "Группа активна",
    "timeline_story_channel_active": "Канал активен",
    "timeline_story_activity_body": "Сообщений: {messages}; активных периодов: {periods}",
    "timeline_story_activity_channel_body": "Публикаций: {posts}; активных периодов: {periods}",
    "timeline_story_resumed": "Активность вернулась",
    "timeline_story_resumed_body": "Активность вернулась после {days} тихих дней",
    "timeline_story_quiet_period": "Долгий тихий период",
    "timeline_story_quiet_body": "Видимых сообщений не было {days} дн.",
    "timeline_story_activity_increased": "Активность выросла",
    "timeline_story_activity_increased_body": "Активнее, чем в предыдущий сопоставимый период",
    "timeline_story_activity_decreased": "Активность снизилась",
    "timeline_story_activity_decreased_body": "Тише, чем в предыдущий сопоставимый период",
    "timeline_story_question": "Найден вопрос",
    "timeline_story_question_body": "В разговоре появился вопрос",
    "timeline_story_unanswered_question": "Вопрос может требовать ответа",
    "timeline_story_unanswered_question_body": "Один открытый вопрос может требовать внимания",
    "timeline_story_plan": "Упомянут план",
    "timeline_story_plan_body": "Появился кандидат на план",
    "timeline_story_promise": "Возможное обещание",
    "timeline_story_promise_body": "Появился кандидат на обещание или договоренность",
    "timeline_story_followup": "Предложено напоминание",
    "timeline_story_followup_body": "Одно открытое напоминание может требовать внимания",
    "timeline_story_reminder_suggested": "Напоминание предложено",
    "timeline_story_reminder_confirmed": "Напоминание подтверждено",
    "timeline_story_reminder_completed": "Напоминание выполнено",
    "timeline_story_reminder_dismissed": "Напоминание отклонено",
    "timeline_story_reminder_body": "Статус напоминания изменился",
    "timeline_story_analysis": "Анализ завершен",
    "timeline_story_analysis_body": "Обзор за период «{period}» обновлен",
    "timeline_story_event": "Событие хронологии",
    "timeline_story_change_counts": "{current} сообщений против {previous} ранее",
    "timeline_day_part_morning": "В основном утром",
    "timeline_day_part_afternoon": "В основном днем",
    "timeline_day_part_evening": "В основном вечером",
    "timeline_day_part_night": "В основном ночью",
    "month_title_01": "Январь",
    "month_title_02": "Февраль",
    "month_title_03": "Март",
    "month_title_04": "Апрель",
    "month_title_05": "Май",
    "month_title_06": "Июнь",
    "month_title_07": "Июль",
    "month_title_08": "Август",
    "month_title_09": "Сентябрь",
    "month_title_10": "Октябрь",
    "month_title_11": "Ноябрь",
    "month_title_12": "Декабрь",
    "month_day_01": "января",
    "month_day_02": "февраля",
    "month_day_03": "марта",
    "month_day_04": "апреля",
    "month_day_05": "мая",
    "month_day_06": "июня",
    "month_day_07": "июля",
    "month_day_08": "августа",
    "month_day_09": "сентября",
    "month_day_10": "октября",
    "month_day_11": "ноября",
    "month_day_12": "декабря",
    "report_created": "Создан",
    "report_messages": "Сообщений проанализировано",
    "report_confidence": "Уверенность",
    "report_completeness": "Полнота",
}
