STRINGS = {
    "app_name": "RelChat",
    "main_title": "RelChat",
    "main_connected": "Telegram подключен",
    "main_not_connected": "Telegram не подключен",
    "main_saved_chats": "Сохраненные чаты",
    "main_reports": "Отчеты",
    "main_followups": "Напоминания",
    "main_running": "Анализ выполняется",
    "main_idle": "Анализ не выполняется",
    "button_analyze": "Проанализировать чат",
    "button_my_chats": "Мои чаты",
    "button_reports": "Отчеты",
    "button_reminders": "Напоминания",
    "button_settings": "Настройки",
    "button_help": "Помощь",
    "button_back": "Назад",
    "button_cancel": "Отмена",
    "button_main": "Главное меню",
    "button_retry": "Повторить",
    "button_run_analysis": "Запустить анализ",
    "button_update_analysis": "Обновить анализ",
    "button_analyze_again": "Проанализировать снова",
    "button_overview": "Обзор",
    "button_insights": "Инсайты",
    "button_timeline": "Хронология",
    "button_activity": "Активность",
    "button_response": "Ритм ответов",
    "button_followups": "Напоминания",
    "button_habits": "Привычки",
    "button_chat_reports": "Отчеты по этому чату",
    "button_chat_reports_short": "Отчеты",
    "button_chat_settings": "Настройки чата",
    "button_delete_local_data": "Удалить локальные данные",
    "button_chat_home": "Экран чата",
    "button_details": "Детали",
    "button_browse_timeline": "Открыть хронологию",
    "button_timeline_chart": "График активности",
    "button_newer": "Новее",
    "button_older": "Старее",
    "button_latest_report": "Последний отчет",
    "button_favorite": "В избранное",
    "button_unfavorite": "Убрать из избранного",
    "button_rename": "Переименовать",
    "button_open_chat": "Открыть чат",
    "button_browse_all": "Все чаты",
    "button_favorites": "Избранное",
    "button_recently_analyzed": "Недавно анализировали",
    "button_saved_chats": "Сохраненные чаты",
    "onboarding_1_title": "Добро пожаловать в RelChat",
    "onboarding_1_body": "RelChat помогает просматривать выбранные переписки через локальные метрики, события, отчеты и напоминания.",
    "onboarding_2_title": "Приватность",
    "onboarding_2_body": "История чатов читается локально через ваш собственный аккаунт Telegram. Сам бот не может читать приватные чаты через Bot API.",
    "onboarding_3_connected": "Telegram подключен. Можно перейти в главное меню.",
    "onboarding_3_missing": "Telegram пока не подключен. Перед загрузкой чатов нужна одна локальная авторизация Telegram.",
    "onboarding_safe_auth": "Не отправляйте сюда коды входа, пароли, API hash, токены бота, файлы сессии или номер телефона.",
    "help_title": "Помощь",
    "privacy_title": "Как работает приватность",
    "auth_title": "Зачем нужна авторизация",
    "metrics_title": "Что означают метрики",
    "limits_title": "Чего RelChat не может знать",
    "troubleshooting_title": "Решение проблем",
    "about_title": "О проекте",
    "empty": "Пока ничего нет.",
    "empty_no_analyzed_chats": "Пока нет проанализированных чатов. Проанализируйте чат, чтобы создать первый экран чата.",
    "empty_no_recent_chats": "Пока нет недавно проанализированных чатов.",
    "empty_no_report": "Для этого чата пока нет отчета. Запустите анализ, чтобы создать обзор и отчет.",
    "empty_no_followups": "Для этого чата пока нет напоминаний.",
    "loading_chats": "Загружаю чаты...",
    "loading_chat_home": "Загружаю сводку чата...",
    "loading_failed": "Не удалось загрузить чаты. Проверьте локальное подключение Telegram и попробуйте снова.",
    "session_missing": "Telegram пока не подключен локально. Завершите локальную авторизацию Telegram и вернитесь сюда.",
    "auth_expired": "Похоже, авторизация Telegram истекла. Подключите аккаунт локально и попробуйте снова.",
    "network_unavailable": "Telegram сейчас недоступен. Проверьте сеть и попробуйте снова.",
    "flood_wait": "Telegram попросил RelChat подождать. Попробуйте позже.",
    "chat_inaccessible": "Этот чат недоступен через подключенный аккаунт Telegram.",
    "expired_navigation": "Этот экран больше недоступен. Вернитесь в главное меню и откройте чат снова.",
    "unknown_action": "Это действие больше недоступно. Вернитесь в главное меню.",
    "analysis_already_running": "Для этого чата уже выполняется анализ.",
    "no_messages": "За выбранный период сообщений не найдено.",
    "invalid_date": "Не удалось распознать дату. Попробуйте 2026-07-01, 01.07.2026, 7 days или 30 days.",
    "cancelled": "Анализ отменен. Уже импортированные локальные сообщения сохранены, завершенный отчет не создан.",
    "database_problem": "Возникла проблема с локальным хранилищем. Проверьте локальную базу данных и попробуйте снова.",
    "unexpected_error": "Что-то пошло не так. Код ошибки: {reference}",
    "destructive_note": "Это влияет только на локальные данные RelChat. Чаты и сообщения в Telegram не удаляются.",
    "chat_type_person": "Человек",
    "chat_type_group": "Группа",
    "chat_type_channel": "Канал",
    "chat_type_unknown": "Чат",
    "chat_home_current": "Текущий обзор",
    "chat_home_changed": "Что изменилось",
    "chat_home_attention": "Требует внимания",
    "chat_home_explore": "Разделы",
    "chat_home_data_quality": "Качество данных",
    "chat_home_no_analysis": "Анализа пока нет.",
    "chat_home_no_analysis_action": "Запустите анализ, чтобы создать обзор, отчет, хронологию и список напоминаний.",
    "chat_home_last_period": "Последний период анализа",
    "chat_home_report_freshness": "Актуальность отчета",
    "chat_home_pending_followups": "Активные напоминания",
    "chat_home_running": "Для этого чата сейчас выполняется анализ.",
    "chat_home_v4_state_stable": "Все выглядит стабильно.",
    "chat_home_v4_state_group_stable": "Активность группы выглядит стабильной.",
    "chat_home_v4_state_channel_stable": "Публикации выглядят стабильными.",
    "chat_home_v4_state_attention": "Есть несколько пунктов, которые стоит проверить.",
    "chat_home_v4_state_long_silence": "Несколько дней не было общения.",
    "chat_home_v4_state_group_long_silence": "Несколько дней не было активности в группе.",
    "chat_home_v4_state_channel_long_silence": "Несколько дней не было публикаций в канале.",
    "chat_home_v4_state_quiet": "Общение стало тише, чем в предыдущий период.",
    "chat_home_v4_state_group_quiet": "Активность группы ниже, чем в предыдущий период.",
    "chat_home_v4_state_channel_quiet": "Публикаций меньше, чем в предыдущий период.",
    "chat_home_v4_state_active": "Общение стало активнее, чем раньше.",
    "chat_home_v4_state_group_active": "Активность группы выше, чем раньше.",
    "chat_home_v4_state_channel_active": "Публикаций стало больше, чем раньше.",
    "chat_home_v4_state_no_analysis": "Анализа пока нет.",
    "chat_home_v4_state_running": "Анализ сейчас выполняется.",
    "chat_home_v4_last_activity": "Последняя активность",
    "chat_home_v4_communication_rhythm": "Ритм общения",
    "chat_home_v4_group_rhythm": "Ритм активности группы",
    "chat_home_v4_posting_cadence": "Ритм публикаций",
    "chat_home_v4_current_activity": "Текущая активность",
    "chat_home_v4_current_group_activity": "Текущая активность группы",
    "chat_home_v4_current_posting": "Текущая активность публикаций",
    "chat_home_v4_next_reminder": "Следующее напоминание",
    "chat_home_v4_last_analysis": "Последний анализ",
    "chat_home_v4_trend": "Тренд",
    "chat_home_v4_attention_section": "Внимание",
    "chat_home_v4_latest_analysis_section": "Последний анализ",
    "chat_home_v4_latest_analysis_value": "Обновлено",
    "chat_home_v4_followup_title": "Напоминания",
    "chat_home_v4_followups_count": "Напоминаний: {count}",
    "chat_home_v4_no_followups_value": "Пока нет предложенных напоминаний.",
    "chat_home_v4_no_reminder_value": "Напоминание не запланировано.",
    "chat_home_v4_no_analysis_title": "Анализа пока нет.",
    "chat_home_v4_no_analysis_body": "Запустите первый анализ, чтобы увидеть инсайты по общению.",
    "chat_home_v4_rhythm_regular": "Регулярный",
    "chat_home_v4_rhythm_bursty": "Всплесками",
    "chat_home_v4_rhythm_quiet": "Тихий",
    "chat_home_v4_cadence_regular": "Регулярный",
    "chat_home_v4_cadence_bursty": "Всплесками",
    "chat_home_v4_cadence_quiet": "Тихий",
    "chat_home_v4_unknown": "Пока недостаточно данных",
    "chat_home_v4_activity_up": "Выше, чем в предыдущий период",
    "chat_home_v4_activity_stable": "Похоже на предыдущий период",
    "chat_home_v4_activity_down": "Ниже, чем в предыдущий период",
    "chat_home_v4_posting_up": "Публикаций больше, чем в предыдущий период",
    "chat_home_v4_posting_stable": "Похоже на предыдущий период",
    "chat_home_v4_posting_down": "Публикаций меньше, чем в предыдущий период",
    "chat_home_v4_recent_unknown": "Пока нет сопоставимого предыдущего периода",
    "chat_home_v4_initiation_one_sided": "Большинство сессий начинает один участник.",
    "chat_home_v4_initiation_balanced": "Начало сессий распределено достаточно ровно.",
    "chat_home_v4_group_initiation_balanced": "Активные периоды начинают разные участники.",
    "chat_home_v4_reply_limited": "Пока недостаточно данных об ответах.",
    "chat_home_v4_reply_observed": "В этот период были ответы.",
    "chat_home_v4_not_used_for_channels": "Не используется для каналов.",
    "chat_home_loading_title": "Загружаю чат...",
    "chat_home_loading_chat": "Загружаю чат",
    "chat_home_loading_report": "Загружаю последний отчет",
    "chat_home_loading_reminders": "Загружаю напоминания",
    "status_active": "Активно",
    "status_quiet": "Тихо",
    "status_attention": "Требует внимания",
    "status_long_silence": "Долгая пауза",
    "status_no_analysis": "Нет анализа",
    "status_loading": "Загрузка",
    "confidence_high": "Высокая",
    "confidence_medium": "Средняя",
    "confidence_low": "Низкая",
    "chat_settings_title": "Настройки чата",
    "chat_settings_body": "Это локальные настройки RelChat для этого чата. Они не меняют чаты или сообщения в Telegram.",
    "chat_settings_manage_hint": "В разделе Мои чаты можно переименовать локально, добавить в избранное или удалить локальные данные RelChat.",
    "chat_settings_favorite": "Избранное",
    "yes": "да",
    "no": "нет",
    "relative_today": "Сегодня",
    "relative_yesterday": "Вчера",
    "relative_tomorrow": "Завтра",
    "relative_days_ago": "{count} дн. назад",
    "relative_in_days": "через {count} дн.",
    "chat_summary_private": "Сводка основана только на наблюдаемых паттернах общения.",
    "chat_summary_group": "Сводка группы показывает активность, участие, вопросы, планы и напоминания.",
    "chat_summary_channel": "Сводка канала показывает публикации, тихие периоды и ритм контента.",
    "chat_summary_messages": "Сообщений в последнем отчете",
    "chat_changed_unavailable": "Сравнение трендов пока недоступно.",
    "chat_attention_clear": "Сейчас нет напоминаний, требующих внимания.",
    "chat_attention_questions": "Вопросы, которые могут требовать ответа",
    "overview_title": "Обзор",
    "overview_current_snapshot": "Текущий обзор",
    "overview_recent_change": "Недавнее изменение",
    "overview_balance": "Баланс",
    "overview_response": "Ритм ответов",
    "overview_attention": "Требует внимания",
    "overview_data_quality": "Качество данных",
    "overview_details_title": "Детали обзора",
    "overview_no_report": "Для этого чата пока нет завершенного отчета.",
    "overview_no_messages": "В этом отчете нет проанализированных сообщений.",
    "overview_private_balanced": "В этот период оба участника общались примерно на сопоставимом уровне.",
    "overview_private_one_sided_initiation": "Когда разговор активен, ответы есть, но большинство сессий начинает один участник.",
    "overview_private_active": "Активности достаточно, чтобы кратко описать наблюдаемые паттерны общения.",
    "overview_group": "В группе достаточно активности, чтобы кратко описать участие, вопросы, планы и напоминания.",
    "overview_channel": "Обзор канала показывает публикации и ритм контента, а не ответы.",
    "overview_limited_sample": "Выборка ограничена, поэтому RelChat не делает выводы с процентами.",
    "overview_recent_missing": "Пока нет сопоставимого предыдущего периода.",
    "overview_recent_limited": "Предыдущий отчет есть, но данных недостаточно для корректного сравнения.",
    "overview_recent_similar": "Активность похожа на предыдущий сопоставимый период.",
    "overview_recent_higher": "Активность выше, чем в предыдущем сопоставимом периоде.",
    "overview_recent_lower": "Активность ниже, чем в предыдущем сопоставимом периоде.",
    "overview_initiation_split": "Начало сессий",
    "overview_reply_participation": "Участие в ответах",
    "overview_planning_balance_unavailable": "Баланс планов и напоминаний по участникам недоступен в этом отчете.",
    "overview_typical_response": "Обычное время ответа",
    "overview_active_response": "Ответы в активном чате",
    "overview_consistency": "Стабильность",
    "overview_consistent": "Ритм ответов в этот период выглядит достаточно стабильным.",
    "overview_varied": "Ритм ответов в этот период заметно меняется.",
    "overview_response_limited": "Недостаточно чередующихся сообщений, чтобы описать ритм ответов.",
    "overview_no_attention": "Сейчас нет нерешенных вопросов, планов, обещаний или подтвержденных напоминаний.",
    "overview_unanswered_questions": "Вопросы без ответа",
    "overview_unresolved_plans": "Планы для проверки",
    "overview_promises_followups": "Обещания и напоминания",
    "overview_confirmed_reminders": "Подтвержденные напоминания",
    "overview_long_silences": "Тихие периоды",
    "overview_average_length": "Средняя длина сообщения",
    "overview_imported_range": "Загруженный диапазон",
    "overview_limitations": "Ограничения",
    "overview_not_enough_for_percent": "Проценты не показаны, потому что выборка мала.",
    "overview_count": "количество",
    "not_available": "недоступно",
    "button_full_analysis": "Полный анализ",
    "button_ai_analysis": "Расширенный ИИ-анализ",
    "button_local_analysis": "Локальный анализ",
    "button_continue_ai": "Продолжить с ИИ",
    "button_use_local_analysis": "Использовать локальный анализ",
    "button_revoke_ai_consent": "Отозвать согласие на ИИ",
    "button_result_details": "Детали",
    "analysis_result_title": "Анализ завершен",
    "analysis_result_local_mode": "Локальный анализ",
    "analysis_result_period": "Период",
    "analysis_result_messages": "Сообщений проанализировано",
    "analysis_result_stands_out": "Что заметно",
    "analysis_result_attention": "Требует внимания",
    "analysis_result_quality": "Качество данных",
    "analysis_result_ai_partial": "Расширенный ИИ-анализ был недоступен, поэтому показан локальный анализ.",
    "analysis_mode_title": "Выберите тип анализа",
    "analysis_mode_body": "Локальный анализ остается на этом устройстве. Расширенный ИИ-анализ может добавить сводку по стилю общения после вашего согласия.",
    "ai_consent_prompt": "Расширенный ИИ-анализ отправляет выбранные сообщения переписки в OpenAI.\nВместо этого можно использовать только локальный анализ.",
    "ai_error_disabled": "Расширенный ИИ-анализ сейчас отключен.",
    "ai_error_missing_key": "Расширенный ИИ-анализ не настроен: отсутствует OpenAI API key.",
    "ai_error_missing_model": "Расширенный ИИ-анализ не настроен: отсутствует название модели.",
    "ai_error_sdk_missing": "Для расширенного ИИ-анализа нужен опциональный Python SDK OpenAI.",
    "ai_error_generic": "Расширенный ИИ-анализ сейчас недоступен.",
    "ai_error_failed": "Расширенный ИИ-анализ завершился безопасной ошибкой. Локальный анализ доступен.",
    "ai_offer_local": "Вместо этого можно использовать только локальный анализ.",
    "ai_communication_analysis": "Анализ общения",
    "ai_activity_analysis": "Анализ активности",
    "ai_communication_score": "Оценка общения",
    "ai_effectiveness_score": "Оценка эффективности",
    "ai_activity_score": "Оценка активности",
    "ai_confidence_line": "Уверенность: {confidence}",
    "ai_confidence_short": "Уверенность",
    "ai_summary_title": "Краткий вывод",
    "ai_strengths_title": "Сильные стороны",
    "ai_weakens_title": "Что мешает диалогу",
    "ai_main_advice": "Главный совет",
    "ai_advice_title": "Советы",
    "ai_weak_replies_title": "Ответы, которые мешали диалогу",
    "ai_scores_title": "Оценки",
    "ai_example": "Пример",
    "ai_no_raw_text_note": "Текст сообщений по умолчанию скрыт.",
    "ai_no_weak_replies": "В этом результате не найдено паттернов, которые заметно мешали диалогу.",
    "ai_severity": "Серьезность",
    "ai_reference": "Ссылка",
    "ai_local_reference": "локальный кандидат",
    "ai_score_formula": "Общая оценка = взвешенные позитивные измерения общения минус штрафы риска, в диапазоне 0-10.",
    "ai_insufficient_data": "Недостаточно данных",
    "ai_score_unreliable": "Недостаточно данных для надежной общей оценки",
    "ai_score_insufficient_explanation": "Недостаточно сопоставимых данных для надежной оценки.",
    "ai_score_cap_shallow": "Оценка ограничена, потому что доступны только поверхностные локальные признаки.",
    "ai_score_cap_deterministic": "Оценка ограничена, потому что детерминированные метрики не понимают смысл сообщений.",
    "ai_score_cap_sampled_ai": "Оценка ограничена, потому что ИИ анализировал выборку, а не весь текст.",
    "ai_score_cap_context": "Оценка ограничена, потому что контекст общения определен с низкой уверенностью.",
    "ai_score_cap_limited_dimensions": "Оценка ограничена, потому что подтверждено слишком мало независимых измерений.",
    "ai_data_title": "Данные",
    "ai_coverage_messages": "Проанализировано {count} сообщений за выбранный период.",
    "ai_selected_period_analyzed": "Проанализирован выбранный период.",
    "ai_sample_used": "Для части выводов использована выборка сообщений.",
    "ai_sample_used_count": "Для части выводов использована выборка из {count} сообщений.",
    "ai_evidence_count": "Свидетельств",
    "ai_limitations_title": "Ограничения",
    "ai_full_analysis_title": "Полный анализ",
    "ai_you_title": "Как вы ведете переписку",
    "ai_other_title": "Как собеседник ведет переписку",
    "ai_consent_status": "Согласие на ИИ",
    "settings_ai_consent_active": "активно",
    "settings_ai_consent_not_active": "не активно",
    "ai_consent_revoked": "Согласие на ИИ отозвано. При следующем расширенном ИИ-анализе RelChat снова спросит разрешение перед отправкой выбранных сообщений в OpenAI.",
    "ai_dimension_reciprocity": "Взаимность",
    "ai_dimension_initiative_balance": "Инициатива",
    "ai_dimension_reply_consistency": "Стабильность ответов",
    "ai_dimension_reply_quality": "Качество ответов",
    "ai_dimension_respectfulness": "Уважительность",
    "ai_dimension_topic_continuation": "Продолжение тем",
    "ai_dimension_question_engagement": "Работа с вопросами",
    "ai_dimension_planning_cooperation": "Согласование планов",
    "ai_dimension_emotional_acknowledgement": "Признание эмоциональных сообщений",
    "ai_dimension_pressure_risk": "Риск давления",
    "ai_dimension_hostility": "Враждебность",
    "ai_dimension_dismissiveness": "Обесценивание",
    "ai_dimension_unresolved_question_rate": "Нерешенные вопросы",
    "ai_dimension_unanswered_question_rate": "Вопросы без ответа",
    "ai_dimension_sarcasm_intensity": "Выраженность сарказма",
    "ai_dimension_unavailable": "Для этой оценки нужен анализ текста.",
    "ai_sarcasm_unavailable": "Недостаточно данных для оценки сарказма.",
    "ai_hostility_unavailable": "Недостаточно данных для оценки враждебности.",
    "ai_dismissiveness_unavailable": "Недостаточно данных для оценки обесценивающих формулировок.",
    "ai_dimension_reciprocity_explanation": "Показывает баланс видимой активности. Это не доказывает равный интерес, теплоту или качество общения.",
    "ai_dimension_initiative_balance_explanation": "Показывает, кто начинает видимые сессии общения. Это не объясняет причину перекоса.",
    "ai_dimension_reply_consistency_explanation": "Показывает доступный ритм ответов и чередование сообщений.",
    "ai_dimension_reply_quality_explanation": "Использует отфильтрованные прямые вопросы и возможности ответа; локальный режим не оценивает полный смысл каждого ответа.",
    "ai_dimension_topic_continuation_explanation": "Показывает повторяющиеся видимые сессии и возможности продолжения тем.",
    "ai_dimension_question_engagement_explanation": "Показывает, сколько прямых вопросов получили реакцию.",
    "ai_dimension_planning_cooperation_explanation": "Показывает явные упоминания планов, обещаний и напоминаний.",
    "ai_dimension_pressure_risk_explanation": "Показывает риск давления по повторным напоминаниям и открытым обещаниям.",
    "severity_low": "низкая",
    "severity_medium": "средняя",
    "severity_high": "высокая",
    "ai_weak_ignored_question": "Прямой вопрос остался без ответа",
    "ai_weak_abrupt_reply": "Резкий ответ",
    "ai_weak_sarcasm": "Сарказм вместо прямого ответа",
    "ai_weak_sarcasm_instead_of_answer": "Сарказм вместо прямого ответа",
    "ai_weak_dismissive": "Обесценивающая формулировка",
    "ai_weak_topic_switch": "Резкая смена темы",
    "ai_weak_low_effort": "Слишком короткий ответ",
    "ai_weak_hostile": "Враждебная формулировка",
    "ai_weak_pressure": "Ответ усиливает давление",
    "ai_weak_missing_acknowledgement": "Важное сообщение осталось без признания",
    "chat_home_details_title": "Детали",
    "chat_home_details_body": "Откройте полный анализ, хронологию, активность, напоминания, предыдущие анализы или локальные настройки чата.",
    "button_change_context": "Изменить тип общения",
    "context_change_title": "Изменить тип общения",
    "context_change_body": "Выберите контекст, который лучше всего подходит этому чату. Ваш выбор переопределит автоматическую классификацию, пока вы не измените его снова.",
    "context_saved": "Тип общения сохранен.",
    "context_rerun_hint": "Запустите анализ снова, чтобы применить его к новому результату.",
    "context_option_romantic": "Романтическое",
    "context_option_friendship": "Дружеское",
    "context_option_family": "Семейное",
    "context_option_work": "Рабочее",
    "context_option_other": "Другое",
    "context_romantic": "Романтическое общение",
    "context_friendship": "Дружеское общение",
    "context_family": "Семейное общение",
    "context_work": "Рабочее общение",
    "context_customer_or_service": "Клиентское или сервисное общение",
    "context_group_social": "Активность группы",
    "context_channel_or_broadcast": "Активность канала или рассылки",
    "context_mixed": "Смешанный контекст общения",
    "context_unknown": "Контекст общения не определен",
    "context_low_confidence_note": "Контекст общения определён приблизительно.",
    "local_context_explanation": "Контекст был выбран или оценен перед анализом.",
    "local_limitation_structure": "Локальный анализ видит структуру переписки, но не понимает смысл каждого ответа.",
    "local_limitation_period": "Использованы локальные детерминированные метрики за период: {period}.",
    "local_uncertainty_reason": "Причину нельзя определить только по сообщениям.",
    "local_uncertainty_no_ai": "ИИ-анализ текста не использовался.",
    "local_summary_no_activity": "Недостаточно видимой активности для вывода об общении.",
    "local_summary_group": "Активность группы описана по локальному количеству сообщений, вопросам, планам и напоминаниям.",
    "local_summary_channel": "Активность канала описана по ритму публикаций и тихим периодам.",
    "local_summary_unanswered": "{count} прямых вопросов не получили видимой реакции после фильтрации слабых совпадений.",
    "local_summary_private_neutral": "В переписке есть видимая активность, но локальный анализ видит только структуру. Равный объем сообщений не доказывает теплоту, интерес, уважительность или сильное общение.",
    "local_summary_romantic_neutral": "В переписке есть видимая активность, но локальный анализ не может надежно определить романтический интерес или эмоциональную теплоту без анализа текста.",
    "local_summary_work_neutral": "Рабочая переписка достаточно активна для структурной сводки, но локальный анализ не может понять, закрывали ли ответы задачу.",
    "local_pattern_visible_activity": "Видимая активность",
    "local_pattern_visible_activity_explanation": "В выбранном периоде достаточно локальной активности для краткого описания базовых паттернов.",
    "local_pattern_both_sides": "Обе стороны участвовали",
    "local_pattern_visible_conversation": "Видимая активность переписки",
    "local_pattern_activity_explanation": "Локальные метрики нашли активность сообщений в выбранном периоде.",
    "local_pattern_work_activity_explanation": "Локальные метрики нашли рабочую активность, но не подтверждают, что задача решена.",
    "local_problem_unanswered_title": "Вопросы без ответа",
    "local_problem_unanswered_explanation": "{count} прямых вопросов не получили видимой реакции после фильтрации слабых совпадений.",
    "local_problem_followups_title": "Открытые напоминания",
    "local_problem_followups_explanation": "{count} открытых напоминаний остались видимыми в этом периоде.",
    "local_weak_ignored_question": "Как минимум один прямой вопрос не получил видимого ответа в выбранном периоде.",
    "local_advice_question_title": "Задайте один ясный вопрос",
    "local_advice_question_explanation": "На один конкретный вопрос проще ответить и проще потом вернуться к нему.",
    "local_advice_question_example": "Можешь подтвердить план на пятницу?",
    "local_advice_next_step_title": "Уточните следующий шаг",
    "local_advice_next_step_explanation": "Когда планы или обещания остаются открытыми, прямое уточнение яснее повторных напоминаний.",
    "local_advice_next_step_example": "Это всё ещё удобно на завтра?",
    "local_advice_work_title": "Сделайте следующий шаг явным",
    "local_advice_work_explanation": "Одним сообщением зафиксируйте задачу, ответственного, ожидаемый результат и срок.",
    "local_advice_work_example": "Задача: отправить финальный файл. Ответственный: Алексей. Срок: пятница 16:00.",
    "local_advice_simple_title": "Сделайте следующее сообщение простым",
    "local_advice_simple_explanation": "Продолжайте одной ясной темой и смотрите, развивает ли собеседник разговор со своей стороны.",
    "local_advice_simple_example": "Как тебе четверг вечером?",
    "local_verdict_uneven_headline": "Разговор был неравномерным.",
    "local_verdict_uneven_explanation": "Локальные метрики показывают, что одна сторона несла больше видимой активности или несколько прямых вопросов не получили видимого ответа.",
    "local_verdict_strong_headline": "Общение выглядело сильным.",
    "local_verdict_strong_explanation": "Такой вывод требует нескольких подтвержденных измерений, а не одного баланса сообщений.",
    "local_verdict_good_headline": "Общение выглядело в целом хорошим.",
    "local_verdict_good_explanation": "Вывод основан на подтвержденных видимых измерениях и ограничен локальными данными.",
    "local_verdict_mixed_headline": "Общение выглядело смешанным.",
    "local_verdict_mixed_explanation": "Некоторые структурные признаки положительные, но данных недостаточно для сильного вывода.",
    "local_verdict_weak_headline": "Общение выглядело слабым.",
    "local_verdict_weak_explanation": "Общение выглядит нестабильным: часть тем остается без завершения, а поддержание разговора распределено неравномерно.",
    "local_verdict_very_weak_headline": "Общение выглядело очень слабым.",
    "local_verdict_very_weak_explanation": "В переписке мало признаков, которые позволили бы назвать общение устойчивым и взаимным.",
    "local_verdict_insufficient_data_headline": "Недостаточно сопоставимых данных.",
    "local_verdict_insufficient_data_explanation": "Видимых данных слишком мало для устойчивого вывода.",
    "local_finding_insufficient": "Видимых данных слишком мало для устойчивого вывода.",
    "local_finding_volume_unbalanced": "Диалог был неравномерным. Большая часть видимого объема сообщений приходится на сторону: {side}.",
    "local_finding_no_restart": "В этот период не было новых стартов разговора со стороны: {side}.",
    "local_finding_equal_volume_not_quality": "Обе стороны писали примерно одинаково часто. Это показывает баланс активности, но не доказывает равный интерес или качество общения.",
    "local_finding_unanswered": "{count} прямых вопросов не получили видимого ответа.",
    "local_finding_followups": "{count} открытых напоминаний остались видимыми в выбранном периоде.",
    "local_finding_no_positive_conclusion": "В этой переписке пока мало признаков, которые позволили бы назвать общение устойчивым и взаимным.",
    "local_finding_work_limited": "В рабочем чате есть видимая активность, но локальные метрики не подтверждают, что задача решена.",
    "local_side_you": "Вы",
    "local_side_other": "Собеседник",
    "local_recommendation_insufficient": "Недостаточно видимых данных для конкретной рекомендации.",
    "local_recommendation_work_clarify": "Уточните задачу, ответственного, ожидаемый результат и срок одним сообщением.",
    "local_recommendation_stop_repeating": "Не отправляйте несколько новых сообщений об одном и том же нерешенном пункте. Задайте один прямой вопрос или дождитесь встречной инициативы.",
    "local_recommendation_reduce_pressure": "Видимая вовлеченность была низкой или неравномерной, поэтому давление вряд ли добавит ясности.",
    "local_recommendation_work_next": "Следующее рабочее сообщение лучше сделать конкретным и явно назначить следующий шаг.",
    "local_recommendation_continue": "Продолжайте ясными прямыми сообщениями и смотрите, развивает ли собеседник темы со своей стороны.",
    "local_strength_comparable_volume": "Участвует с сопоставимым видимым объемом сообщений.",
    "local_participant_summary_insufficient": "Недостаточно видимых сообщений для сводки.",
    "local_participant_summary_none": "В выбранном периоде нет видимых сообщений с этой стороны.",
    "local_participant_summary_count": "Видимых сообщений в выбранном периоде: {count}.",
    "local_participant_pattern_none": "В выбранном периоде нет видимых сообщений с этой стороны.",
    "local_participant_pattern_carries_volume": "Несет большую часть видимого объема сообщений в этот период.",
    "local_participant_pattern_fewer_messages": "Участвует меньшим количеством видимых сообщений в этот период.",
    "local_participant_pattern_work_equal_volume": "Участвует с похожим видимым объемом сообщений; это не доказывает, что рабочая задача решена.",
    "local_participant_pattern_similar_volume": "Участвует с похожим видимым объемом сообщений.",
    "local_improvement_one_question": "Задавайте один ясный вопрос за раз, когда нужен прямой ответ.",
    "local_improvement_answer_questions": "На прямые вопросы стоит отвечать ясно, когда ответ виден в переписке.",
    "response_bucket_minutes": "в течение нескольких минут",
    "response_bucket_hour": "примерно в течение часа",
    "response_bucket_hours": "в течение нескольких часов",
    "response_bucket_day": "в течение того же дня",
    "response_bucket_over_day": "больше дня",
    "chat_reports_title": "Отчеты по этому чату",
    "my_chats_title": "Мои чаты",
    "my_chats_choose": "Выберите чат.",
    "my_chats_choose_section": "Выберите раздел.",
    "my_chats_favorites": "Избранное",
    "my_chats_recent": "Недавно анализировали",
    "my_chats_saved": "Сохраненные чаты",
    "module_coming_soon": "Скоро",
    "module_experimental": "Экспериментально",
    "module_not_included": "Не включено в этот отчет",
    "section_timeline_title": "Хронология",
    "section_activity_title": "Активность",
    "section_response_title": "Ритм ответов",
    "section_followups_title": "Напоминания",
    "section_habits_title": "Привычки",
    "section_reports_title": "Отчеты",
    "section_unavailable_body": "Этот экран подготовлен для Product UX v3, но расчет не включен в выбранный отчет.",
    "section_coming_soon_body": "Этот раздел подготовлен для будущего релиза и пока не показывает сгенерированные результаты.",
    "section_channel_hidden_body": "Этот раздел скрыт для каналов: ритм ответов и начало сессий не имеют смысла без импортированных ответов.",
    "selected_prefix": "Выбрано:",
    "timeline_private_note": "Показывает наблюдаемый ритм общения между двумя участниками. RelChat не делает выводов о чувствах или намерениях.",
    "timeline_group_note": "Показывает активность группы, тихие периоды, вопросы, планы и напоминания без формулировок про отношения.",
    "timeline_channel_note": "Показывает публикации и тихие периоды. Баланс ответов и начало сессий скрыты для каналов.",
    "timeline_empty": "Данных для хронологии пока нет. Запустите анализ после импорта сообщений, чтобы создать периоды активности и отметки событий.",
    "timeline_privacy_note": "Текст сообщений в хронологии не показывается.",
    "timeline_analyzed_period": "Период анализа",
    "timeline_most_active": "Самый активный период",
    "timeline_longest_silence": "Самая длинная пауза",
    "timeline_meaningful_events": "Значимые события",
    "timeline_recent_change": "Недавнее изменение",
    "timeline_recent_higher": "Активность выросла по сравнению с предыдущим активным периодом.",
    "timeline_recent_lower": "Активность снизилась по сравнению с предыдущим активным периодом.",
    "timeline_recent_similar": "Активность похожа на предыдущий активный период.",
    "timeline_recent_limited": "Для сравнения недавних изменений нужно больше сообщений.",
    "timeline_recent_unavailable": "Пока недостаточно истории для сравнения.",
    "timeline_filter": "Фильтр",
    "timeline_filter_all": "Все",
    "timeline_filter_activity": "Активность",
    "timeline_filter_questions": "Вопросы",
    "timeline_filter_plans": "Планы",
    "timeline_filter_followups": "Напоминания",
    "timeline_filter_silences": "Паузы",
    "timeline_empty_filter": "Для этого фильтра пока нет записей хронологии.",
    "timeline_no_entries": "Нет записей",
    "timeline_showing": "Показано",
    "timeline_event_activity": "Период активности",
    "timeline_event_quiet": "Тихий период",
    "timeline_event_silence": "Долгая пауза",
    "timeline_event_question": "Найден вопрос",
    "timeline_event_unanswered": "Вопрос может требовать ответа",
    "timeline_event_plan": "Возможный план",
    "timeline_event_promise": "Возможное обещание",
    "timeline_event_followup": "Кандидат для напоминания",
    "timeline_event_reminder": "Подтвержденное напоминание",
    "timeline_event_analysis": "Анализ завершен",
    "timeline_sender": "Отправитель",
    "timeline_participant": "Участник",
    "timeline_member": "Участник",
    "timeline_period": "Период",
    "timeline_gap": "Пауза",
    "timeline_report_period": "Период отчета",
    "timeline_source_message": "Метка сообщения",
    "timeline_rule_source": "Правило",
    "timeline_chart_caption": "График активности RelChat. Текст сообщений не включен.",
    "timeline_chart_failed": "Не удалось создать график активности сейчас. Текстовая хронология по-прежнему доступна.",
    "timeline_empty_story": "Истории хронологии пока нет. Запустите анализ после импорта сообщений, чтобы увидеть, как менялась активность.",
    "timeline_story_conversation_active": "Разговор активен",
    "timeline_story_group_active": "Группа активна",
    "timeline_story_channel_active": "Канал активен",
    "timeline_story_activity_body": "Сообщений: {messages}; активных периодов: {periods}",
    "timeline_story_activity_channel_body": "Публикаций: {posts}; активных периодов: {periods}",
    "timeline_story_resumed": "Активность вернулась",
    "timeline_story_resumed_body": "Активность вернулась после {days} тихих дней",
    "timeline_story_quiet_period": "Долгий тихий период",
    "timeline_story_quiet_body": "Видимых сообщений не было {days} дн.",
    "timeline_story_activity_increased": "Активность выросла",
    "timeline_story_activity_increased_body": "Активнее, чем в предыдущий сопоставимый период",
    "timeline_story_activity_decreased": "Активность снизилась",
    "timeline_story_activity_decreased_body": "Тише, чем в предыдущий сопоставимый период",
    "timeline_story_question": "Найден вопрос",
    "timeline_story_question_body": "В разговоре появился вопрос",
    "timeline_story_unanswered_question": "Вопрос может требовать ответа",
    "timeline_story_unanswered_question_body": "Один открытый вопрос может требовать внимания",
    "timeline_story_plan": "Упомянут план",
    "timeline_story_plan_body": "Появился кандидат на план",
    "timeline_story_promise": "Возможное обещание",
    "timeline_story_promise_body": "Появился кандидат на обещание или договоренность",
    "timeline_story_followup": "Предложено напоминание",
    "timeline_story_followup_body": "Одно открытое напоминание может требовать внимания",
    "timeline_story_reminder_suggested": "Напоминание предложено",
    "timeline_story_reminder_confirmed": "Напоминание подтверждено",
    "timeline_story_reminder_completed": "Напоминание выполнено",
    "timeline_story_reminder_dismissed": "Напоминание отклонено",
    "timeline_story_reminder_body": "Статус напоминания изменился",
    "timeline_story_analysis": "Анализ завершен",
    "timeline_story_analysis_body": "Обзор за период «{period}» обновлен",
    "timeline_story_event": "Событие хронологии",
    "timeline_story_change_counts": "{current} сообщений против {previous} ранее",
    "timeline_day_part_morning": "В основном утром",
    "timeline_day_part_afternoon": "В основном днем",
    "timeline_day_part_evening": "В основном вечером",
    "timeline_day_part_night": "В основном ночью",
    "month_title_01": "Январь",
    "month_title_02": "Февраль",
    "month_title_03": "Март",
    "month_title_04": "Апрель",
    "month_title_05": "Май",
    "month_title_06": "Июнь",
    "month_title_07": "Июль",
    "month_title_08": "Август",
    "month_title_09": "Сентябрь",
    "month_title_10": "Октябрь",
    "month_title_11": "Ноябрь",
    "month_title_12": "Декабрь",
    "month_day_01": "января",
    "month_day_02": "февраля",
    "month_day_03": "марта",
    "month_day_04": "апреля",
    "month_day_05": "мая",
    "month_day_06": "июня",
    "month_day_07": "июля",
    "month_day_08": "августа",
    "month_day_09": "сентября",
    "month_day_10": "октября",
    "month_day_11": "ноября",
    "month_day_12": "декабря",
    "button_compare_periods": "Сравнить периоды",
    "button_previous_period": "Предыдущий период",
    "button_next_period": "Следующий период",
    "button_back_to_analysis": "Назад к анализу",
    "button_not_now": "Не сейчас",
    "ai_verdict_title": "Вывод",
    "ai_direct_findings_title": "Прямые наблюдения",
    "verdict_strong": "Сильный",
    "verdict_good": "Хороший",
    "verdict_mixed": "Смешанный",
    "verdict_weak": "Слабый",
    "verdict_very_weak": "Очень слабый",
    "verdict_insufficient_data": "Недостаточно данных",
    "comparison_title": "По сравнению с предыдущим периодом",
    "comparison_not_enough": "Недостаточно сопоставимых данных.",
    "comparison_overall": "Итог",
    "comparison_overall_better": "Этот разговор прошёл лучше обычного.",
    "comparison_overall_worse": "Этот разговор прошёл хуже обычного.",
    "comparison_no_substantial_changes": "Существенных изменений нет.",
    "comparison_metric_message_count": "Количество сообщений",
    "comparison_metric_sessions_started_by_you": "Сессии, начатые вами",
    "comparison_metric_sessions_started_by_other": "Сессии, начатые собеседником",
    "comparison_metric_initiative_balance": "Баланс инициативы",
    "comparison_metric_response_time": "Скорость ответа",
    "comparison_metric_response_consistency": "Стабильность ответов",
    "comparison_metric_average_reply_length": "Средняя длина ответа",
    "comparison_metric_question_engagement": "Работа с вопросами",
    "comparison_metric_unanswered_question_rate": "Доля вопросов без ответа",
    "comparison_metric_topic_continuation": "Продолжение тем",
    "comparison_metric_planning_activity": "Активность планирования",
    "comparison_metric_follow_up_activity": "Активность напоминаний",
    "comparison_metric_sarcasm_intensity": "Выраженность сарказма",
    "comparison_metric_dismissive_low_effort_patterns": "Обесценивающие или слабые ответы",
    "comparison_metric_pressure_risk": "Риск давления",
    "comparison_metric_communication_score": "Оценка общения",
    "comparison_change_sessions_started_by_other_worsened": "Инициатива снизилась",
    "comparison_change_sessions_started_by_other_improved": "Инициатива собеседника выросла",
    "comparison_change_average_reply_length_worsened": "Ответы стали короче",
    "comparison_change_average_reply_length_improved": "Ответы стали длиннее после очень короткого уровня",
    "comparison_change_unanswered_question_rate_worsened": "Больше вопросов осталось без ответа",
    "comparison_change_unanswered_question_rate_improved": "Меньше вопросов осталось без ответа",
    "comparison_change_response_time_stable": "Скорость ответов почти не изменилась",
    "comparison_change_communication_score_worsened": "Оценка общения снизилась",
    "comparison_change_communication_score_improved": "Оценка общения выросла",
    "important_chat_label": "Важный чат",
    "important_chats_title": "Важные чаты",
    "important_mark": "Отметить как важный",
    "important_remove": "Убрать из важных",
    "important_empty": "Важных чатов пока нет.",
    "automation_analysis": "Автоматический анализ",
    "automation_notifications": "Автоматические уведомления",
    "automation_disable_chat": "Отключить для этого чата",
    "automation_disable_all": "Отключить все автоматические анализы",
    "automation_pause_24h": "Приостановить на 24 часа",
    "conversation_paused_title": "Недавний разговор, похоже, завершился",
    "conversation_paused_question": "Проанализировать разговор?",
    "automation_completed": "Анализ выполнен автоматически",
    "automation_disabled": "Автоматический анализ отключён",
    "quiet_hours": "Тихие часы",
    "quiet_start": "Начало",
    "quiet_end": "Конец",
    "minimum_new_messages": "Минимум новых сообщений",
    "inactivity_threshold": "Пауза без новых сообщений",
    "automation_mode_local": "Только локальный анализ",
    "automation_mode_ai": "ИИ-анализ",
    "automation_analysis_mode": "Режим анализа",
    "automation_cooldown": "Период ожидания",
    "automation_last": "Последний автоматический анализ",
    "automation_pending_count": "Новых сообщений ожидает",
    "automation_defaults_title": "Настройки автоматического анализа",
    "automation_master_switch": "Главный переключатель автоматического анализа",
    "automation_suggest": "Сначала предлагать",
    "automation_auto_run": "Запускать автоматически",
    "automation_ai_consent_required": "Согласие на ИИ отсутствует или отозвано. RelChat не отправляет сообщения в OpenAI без разрешения.",
    "button_why_conclusion": "Почему такой вывод?",
    "participant_you": "ВЫ",
    "participant_other": "СОБЕСЕДНИК",
    "semantic_scope_limitation": "Это относится только к выбранному чату и периоду.",
    "semantic_no_impact_available": "По доступным данным нельзя оценить влияние на диалог.",
    "semantic_insufficient_generic": "Недостаточно данных для уверенного смыслового вывода.",
    "interpretation_level_observed": "Напрямую видно в явных сообщениях.",
    "interpretation_level_supported": "Хорошо поддержано несколькими наблюдаемыми признаками.",
    "interpretation_level_ambiguous": "Не подтверждено или неоднозначно; это нельзя считать фактом.",
    "sarcasm_label": "Сарказм",
    "irony_label": "Ирония",
    "sarcasm_playful_label": "Игровой сарказм",
    "sarcasm_defensive_label": "Защитный сарказм",
    "sarcasm_dismissive_label": "Обесценивающий сарказм",
    "sarcasm_hostile_label": "Враждебный сарказм",
    "aggression_irritation_label": "Раздражение",
    "aggression_conflict_label": "Конфликт",
    "aggression_verbal_label": "Вербальная агрессия",
    "influence_pressure_label": "Давление",
    "influence_persuasion_label": "Убеждение",
    "influence_possible_manipulation_label": "Возможное давление через обязательство",
    "interest_signs_label": "Признаки личной заинтересованности",
    "supporting_signs_label": "Поддерживающие признаки",
    "contradicting_signs_label": "Противоречащие признаки",
    "alternative_explanation_label": "Альтернативное объяснение",
    "directly_visible_label": "Что видно напрямую",
    "possible_interpretation_label": "Возможная интерпретация",
    "not_proven_fact_label": "Это не является доказанным фактом.",
    "not_enough_confident_conclusion": "Недостаточно данных для уверенного вывода.",
    "sarcasm_summary_ambiguous": "Есть неоднозначные маркеры юмора, но контекста недостаточно, чтобы надежно назвать их сарказмом.",
    "sarcasm_summary_insufficient": "Недостаточно данных, чтобы надёжно определить сарказм.",
    "sarcasm_summary_playful": "Сарказм выглядит игровым и скорее поддерживает контакт, чем атакует.",
    "sarcasm_summary_dismissive": "Несколько признаков указывают на обесценивающий сарказм, который закрывает или ослабляет серьезную тему.",
    "sarcasm_summary_dismissive_local": "Несколько формулировок могут восприниматься как саркастические или обесценивающие, но локальный режим не может надежно определить тон или намерение.",
    "sarcasm_summary_hostile": "Сарказм выглядит враждебным и работает как косвенная агрессия.",
    "sarcasm_summary_mixed": "Сарказм заметен как паттерн «{presence}», но его направление смешанное.",
    "sarcasm_impact_playful": "Совместный игровой сарказм может поддерживать легкий контакт, если обоим участникам он комфортен.",
    "sarcasm_impact_bonding": "Сарказм для сближения может облегчать переписку и не обязательно ухудшает ее.",
    "sarcasm_impact_defensive": "Защитный сарказм может помогать уходить от прямого ответа.",
    "sarcasm_impact_dismissive": "Обесценивающий сарказм может обесценить вопрос и завершить тему вместо развития разговора.",
    "sarcasm_impact_hostile": "Враждебный сарказм может работать как косвенная агрессия и усиливать напряжение.",
    "sarcasm_impact_mixed": "Влияние сарказма смешанное, его нужно читать вместе с ближайшим контекстом.",
    "alternative_shared_humour": "Это может быть общий юмор, если такой стиль привычен обоим участникам.",
    "alternative_plain_joke": "Это может быть обычная шутка, а не сарказм.",
    "alternative_conflict_not_aggression": "Это может быть обычный конфликт или граница, а не агрессия.",
    "alternative_clumsy_request": "Это может быть неловкая просьба, а не намеренная тактика влияния.",
    "alternative_stress": "Стресс или срочность могут частично объяснять формулировки.",
    "alternative_friendliness": "Это может быть дружелюбное тепло, а не романтический интерес.",
    "alternative_contextual_politeness": "Часть признаков может отражать вежливость или контекст, а не личный интерес.",
    "aggression_summary_insufficient": "Недостаточно данных, чтобы надежно оценить агрессию или враждебность.",
    "aggression_summary_assertiveness": "В формулировках видна уверенная граница как паттерн «{frequency}», сама по себе это не враждебность.",
    "aggression_summary_frustration": "Видна фрустрация как паттерн «{frequency}», но фрустрация не равна агрессии.",
    "aggression_summary_irritation": "Видно раздражение как паттерн «{frequency}».",
    "aggression_summary_conflict": "Виден конфликт как паттерн «{frequency}».",
    "aggression_summary_verbal_aggression": "Видна прямая вербальная агрессия как паттерн «{frequency}».",
    "aggression_summary_hostility": "Видны враждебные формулировки как паттерн «{frequency}».",
    "aggression_summary_mixed": "Видны смешанные конфликтные сигналы как паттерн «{frequency}».",
    "aggression_impact_direct": "Это влияет на диалог, потому что формулировки направлены на собеседника, а не только на проблему.",
    "aggression_impact_assertive": "Уверенные границы могут прояснять пределы без враждебности.",
    "aggression_impact_frustration": "Фрустрация может добавлять напряжение, но не доказывает враждебное намерение.",
    "influence_summary_ambiguous": "Сигналы влияния неоднозначны и не поддерживают уверенный вывод о манипуляции.",
    "influence_summary_insufficient": "Недостаточно данных для анализа убеждения, давления или манипуляции.",
    "influence_summary_persuasion": "Видимый паттерн похож на убеждение через {strategy}.",
    "influence_summary_pressure": "Видимый паттерн похож на давление через {strategy}.",
    "influence_summary_possible_manipulation": "Некоторые ответы могут создавать давление через вину или обязательство: {strategy}. Намерение нельзя определить только по тексту.",
    "influence_summary_clear_manipulative_pattern": "Повторяющийся паттерн влияния ограничивает пространство для отказа через {strategy}. Это описание формулировок, а не вывод о намерениях.",
    "influence_strategy_guilt_induction_after_reluctance": "вину или обязательство после нежелания",
    "influence_strategy_repeated_request_after_refusal": "повтор просьбы после отказа",
    "influence_strategy_urgency_pressure": "давление срочностью",
    "influence_strategy_transparent_reason_giving": "открытые аргументы и просьбу",
    "influence_effect_persuasion": "Убеждение может быть нормальным, если у другого человека остается свободный выбор.",
    "influence_effect_pressure": "Давление затрудняет отказ и может снижать доверие.",
    "influence_effect_possible_manipulation": "Если эмоциональный рычаг повторяется, это может ограничивать честный выбор.",
    "influence_effect_clear_manipulative_pattern": "Такой паттерн может искажать ответственность или ограничивать возможность свободного выбора.",
    "interest_summary_not_applicable": "Оценка возможного романтического интереса не применима к этому контексту общения.",
    "interest_summary_ambiguous": "Есть отдельные признаки личной заинтересованности, но они слишком смешанные для уверенного вывода.",
    "interest_summary_insufficient": "В этой переписке недостаточно данных, чтобы оценить возможную личную заинтересованность.",
    "interest_summary_moderate": "Есть несколько признаков личной заинтересованности, но они не доказывают чувства или намерения.",
    "interest_summary_strong": "Признаки личной заинтересованности в этом периоде сильные, но чувства и намерения всё равно не являются доказанным фактом.",
    "interest_not_proven_limitation": "Это не доказательство конкретных чувств или намерений.",
    "signal_sarcasm_marker": "саркастичная или ироничная формулировка",
    "signal_sarcasm_quotes": "кавычки использованы обесценивающе",
    "signal_playful_sarcasm": "игровой маркер рядом с сарказмом",
    "signal_dismissive_sarcasm": "сарказм рядом с вопросом или закрытием темы",
    "signal_threat": "явный маркер угрозы",
    "signal_insult": "явный маркер оскорбления",
    "signal_aggressive_command": "срочное повторное требование",
    "signal_frustration": "явная фрустрация",
    "signal_assertive_boundary": "формулировка уверенной границы",
    "signal_refusal": "явный отказ",
    "signal_transparent_persuasion": "аргументированная просьба",
    "signal_guilt_pressure": "давление виной или обязательством",
    "signal_urgency_pressure": "давление срочностью",
    "signal_request_after_refusal": "просьба повторена после отказа",
    "signal_affectionate_language": "теплая или ласковая формулировка",
    "signal_personal_question": "личный вопрос",
    "signal_private_invitation": "приглашение вдвоем",
    "signal_reciprocal_initiation": "паттерн встречной инициативы",
    "signal_refusal_or_reluctance": "отказ или нежелание",
    "signal_explicit_sarcasm": "явная метка сарказма или иронии",
    "finding_title_sarcasm_playful": "Виден игровой сарказм",
    "finding_title_sarcasm_bonding": "Виден сближающий сарказм",
    "finding_title_sarcasm_defensive": "Виден защитный сарказм",
    "finding_title_sarcasm_dismissive": "Обесценивающий сарказм мешает прямому ответу",
    "finding_title_sarcasm_dismissive_local": "Есть потенциально саркастические или обесценивающие формулировки",
    "finding_title_sarcasm_hostile": "Виден враждебный сарказм",
    "finding_title_sarcasm_mixed": "Сарказм виден, но его направление смешанное",
    "finding_title_aggression_assertiveness": "Видны уверенные границы",
    "finding_title_aggression_frustration": "Видна фрустрация",
    "finding_title_aggression_irritation": "Видно раздражение",
    "finding_title_aggression_conflict": "Виден конфликт",
    "finding_title_aggression_verbal_aggression": "Видна прямая вербальная агрессия",
    "finding_title_aggression_hostility": "Видны враждебные формулировки",
    "finding_title_aggression_mixed": "Видны смешанные конфликтные сигналы",
    "finding_title_influence_persuasion": "Видно убеждение",
    "finding_title_influence_pressure": "Видно давление",
    "finding_title_influence_possible_manipulation": "Возможно давление через обязательство",
    "finding_title_influence_clear_manipulative_pattern": "Повторяется давление на возможность выбора",
    "finding_title_possible_interest": "Есть признаки личной заинтересованности",
    "finding_observation_count": "{count} свидетельств поддерживают вывод типа «{evidence_type}».",
    "semantic_type_sarcasm": "сарказм",
    "semantic_type_aggression": "агрессия",
    "semantic_type_influence": "влияние",
    "semantic_type_possible_interest": "возможный интерес",
    "advice_sarcasm_title": "Вернитесь к прямому вопросу",
    "advice_sarcasm_explanation": "Если сарказм мешает получить ответ, коротко признайте шутку и спокойно вернитесь к конкретному вопросу.",
    "advice_aggression_title": "Обозначьте ясную границу",
    "advice_aggression_explanation": "На прямую агрессию лучше ответить границей и остановить обмен, если форма обращения не меняется.",
    "advice_pressure_title": "Не повторяйте ту же просьбу",
    "advice_pressure_explanation": "После явного отказа не повторяйте ту же просьбу в другой форме; спросите, что приемлемо, или отступите.",
    "advice_interest_title": "Проясняйте интерес без давления",
    "advice_interest_explanation": "Если вы хотите показать личный интерес, сделайте одно ясное приглашение и оставьте место для настоящего ответа.",
    "advice_clarity_title": "Проясните прямо",
    "advice_clarity_explanation": "Напишите одно короткое сообщение: в чем вопрос, что именно нужно и какой следующий шаг.",
    "local_advice_semantic_example": "Я понял шутку, но мне всё ещё важен прямой ответ.",
    "local_limitation_semantic_boundary": "Локальный режим отмечает только явные или повторяющиеся формулировки. Сложный смысл, сарказм, давление или интерес без ясных признаков остаются неопределенными.",
    "personal_profile_title": "Как вы общаетесь с этим человеком именно здесь",
    "profile_period_limitation": "Это описывает поведение только в этом чате и периоде.",
    "profile_not_personality": "Это не постоянная характеристика личности.",
    "profile_summary_limited": "В этом периоде мало подтвержденных данных о вашем стиле общения.",
    "profile_summary_available": "В этой переписке есть подтвержденный паттерн вашего поведения.",
    "profile_summary_from_observation": "{observation}",
    "profile_dimension_warmth": "Теплота",
    "profile_dimension_directness": "Прямота",
    "profile_dimension_initiative": "Инициатива",
    "profile_dimension_responsiveness": "Отзывчивость",
    "profile_dimension_question_engagement": "Работа с вопросами",
    "profile_dimension_topic_continuation": "Продолжение тем",
    "profile_dimension_message_detail": "Подробность сообщений",
    "profile_dimension_emotional_acknowledgement": "Эмоциональное подтверждение",
    "profile_dimension_humour": "Юмор",
    "profile_dimension_sarcasm": "Сарказм",
    "profile_dimension_planning_clarity": "Ясность планирования",
    "profile_dimension_conflict_style": "Стиль конфликта",
    "profile_dimension_repair_attempts": "Попытки восстановления",
    "profile_dimension_pressure_risk": "Риск давления",
    "profile_dimension_persuasion_style": "Стиль убеждения",
    "profile_dimension_boundary_respect": "Уважение границ",
    "profile_dimension_unknown": "Наблюдаемое поведение",
    "profile_initiative_high": "В этой переписке вы участвуете чаще собеседника.",
    "profile_initiative_low": "В этом периоде вы участвуете реже, чем собеседник.",
    "profile_initiative_balanced": "Ваша активность примерно сбалансирована с собеседником.",
    "profile_detail_user_longer": "Ваши сообщения обычно подробнее сообщений собеседника.",
    "profile_detail_user_shorter": "Ваши сообщения обычно короче сообщений собеседника.",
    "profile_detail_similar": "Подробность ваших сообщений в целом похожа на подробность сообщений собеседника.",
    "profile_questions_frequent": "Вы часто задаете прямые или уточняющие вопросы ({count}).",
    "profile_questions_some": "Вы задаете несколько прямых вопросов ({count}).",
    "profile_questions_few": "В этой переписке вы чаще передаете информацию, чем задаете прямые вопросы.",
    "profile_planning_visible": "Вы используете конкретные формулировки планирования.",
    "profile_planning_work_limited": "В рабочем контексте конкретики планирования в видимом периоде мало.",
    "profile_planning_limited": "Конкретики планирования в видимом периоде мало.",
    "profile_sarcasm_observation": "В вашей переписке есть {direction}; это описание периода, а не личности.",
    "profile_influence_observation": "В вашем видимом стиле влияния есть {category}.",
    "profile_conflict_observation": "Конфликтные формулировки лучше всего классифицировать как {kind}.",
    "sarcasm_direction_playful": "игровой сарказм",
    "sarcasm_direction_bonding": "сближающий сарказм",
    "sarcasm_direction_defensive": "защитный сарказм",
    "sarcasm_direction_dismissive": "обесценивающий сарказм",
    "sarcasm_direction_hostile": "враждебный сарказм",
    "sarcasm_direction_mixed": "смешанный сарказм",
    "influence_category_persuasion": "убеждение",
    "influence_category_pressure": "давление",
    "influence_category_possible_manipulation": "возможное давление через обязательство",
    "influence_category_clear_manipulative_pattern": "повторяющееся давление на возможность выбора",
    "aggression_type_assertiveness": "уверенную границу",
    "aggression_type_frustration": "фрустрацию",
    "aggression_type_irritation": "раздражение",
    "aggression_type_conflict": "конфликт",
    "aggression_type_verbal_aggression": "вербальную агрессию",
    "aggression_type_hostility": "враждебность",
    "aggression_type_mixed": "смешанный конфликт",
    "cross_chat_observation": "{dimension} чаще проявляется в контексте «{context}» ({count} подтвержденных снимков).",
    "cross_chat_no_raw_text": "Профиль по разным чатам использует только агрегаты и не содержит сырой текст.",
    "cross_chat_aggregate_only": "Этот профиль основан только на подтвержденных агрегированных снимках.",
    "communication_story_title": "История общения",
    "story_what_is_happening_title": "Что происходит",
    "story_main_driver_title": "Что в основном движет перепиской",
    "story_you_title": "Как вы общаетесь",
    "story_other_title": "Как отвечает собеседник",
    "story_semantic_dynamics_title": "Смысловая динамика",
    "story_uncertainties_title": "Что остается неопределенным",
    "story_user_limited": "В этом периоде мало подтвержденных данных о вашем стиле.",
    "story_recurrence_limited": "Повторяемость можно утверждать только после нескольких сопоставимых периодов.",
    "story_happening_limited": "Видимого общения слишком мало для надежной истории.",
    "story_happening_with_friction": "В переписке есть заметная точка трения: {finding}.",
    "story_happening_work": "Рабочую переписку уже можно оценивать с точки зрения эффективности и ясности.",
    "story_happening_family": "Семейная переписка оценивается по поддержке, уважению, практическим вопросам и восстановлению контакта после напряжения.",
    "story_happening_general": "В переписке видно участие, но качество общения зависит не только от объема.",
    "story_driver_problem": "Главный фактор — наблюдаемая проблема: {finding}.",
    "story_driver_positive": "Главный фактор — подтвержденный позитивный или нейтральный паттерн: {finding}.",
    "story_driver_limited": "Главный фактор нельзя определить по доступным данным.",
    "story_other_limited": "Паттерн ответов собеседника в этом периоде недостаточно ясен.",
    "story_other_participates": "Собеседник заметно участвует в обмене.",
    "story_other_reacts_less": "Собеседник в этом периоде выглядит скорее реактивным, чем активным.",
    "story_uncertainty_general": "Причину паттерна нельзя определить только по сообщениям.",
    "why_conclusion_title": "Почему такой вывод?",
    "why_no_evidence_findings": "В этом результате нет подтвержденных выводов, которые можно разобрать по свидетельствам.",
    "why_observed_title": "Что видно напрямую",
    "why_interpretation_title": "Возможная интерпретация",
    "why_supporting_evidence_title": "Поддерживающие признаки",
    "why_alternative_title": "Альтернативное объяснение",
    "why_confidence_title": "Уверенность",
    "why_limitations_title": "Ограничения",
    "why_scope_title": "Область данных",
    "evidence_scope_full_history": "вся история",
    "evidence_scope_recent_window": "недавнее окно",
    "evidence_scope_recurring_across_periods": "повторяется в периодах",
    "evidence_scope_selected_period": "выбранный период",
    "why_observed_limited": "Наблюдение ограничено выбранными данными.",
    "why_interpretation_limited": "Интерпретация ограничена или недоступна.",
    "evidence_line": "{evidence_type}, {sender}: {description}",
    "evidence_line_without_description": "{evidence_type}, {sender}",
    "evidence_type_explicit_wording": "явная формулировка",
    "evidence_type_contextual_sequence": "контекстная последовательность",
    "evidence_type_repeated_pattern": "повторяющийся паттерн",
    "evidence_type_participant_comparison": "сравнение участников",
    "evidence_type_period_comparison": "сравнение периодов",
    "evidence_type_response_behavior": "поведение ответа",
    "evidence_type_event_pattern": "событийный паттерн",
    "evidence_type_semantic_pattern": "смысловой паттерн",
    "evidence_type_historical_recurrence": "историческое повторение",
    "evidence_desc_sarcasm_marker": "саркастичная или ироничная формулировка",
    "evidence_desc_dismissive_quotation_pattern": "кавычки использованы обесценивающе",
    "evidence_desc_playful_sarcasm_marker": "игровой маркер рядом с сарказмом",
    "evidence_desc_sarcasm_after_question_or_topic_shutdown": "сарказм рядом с вопросом или закрытием темы",
    "evidence_desc_explicit_threat_marker": "явный маркер угрозы",
    "evidence_desc_explicit_insult_marker": "явный маркер оскорбления",
    "evidence_desc_urgent_repeated_command": "срочное повторное требование",
    "evidence_desc_explicit_frustration_marker": "явный маркер фрустрации",
    "evidence_desc_assertive_boundary_marker": "маркер уверенной границы",
    "evidence_desc_explicit_refusal_marker": "явный отказ",
    "evidence_desc_reasoned_request_marker": "аргументированная просьба",
    "evidence_desc_guilt_or_obligation_pressure_marker": "давление виной или обязательством",
    "evidence_desc_urgency_pressure_marker": "давление срочностью",
    "evidence_desc_request_repeated_after_refusal": "просьба повторена после отказа",
    "evidence_desc_affectionate_language_marker": "теплая или ласковая формулировка",
    "evidence_desc_personal_question_marker": "личный вопрос",
    "evidence_desc_private_invitation_marker": "приглашение вдвоем",
    "evidence_desc_reciprocal_initiation_pattern": "паттерн встречной инициативы",
    "evidence_desc_refusal_or_reluctance_marker": "отказ или нежелание",
    "timeline_story_semantic_sarcasm_playful": "Появился игровой сарказм",
    "timeline_story_semantic_sarcasm_dismissive": "Появился обесценивающий сарказм",
    "timeline_story_semantic_sarcasm_changed": "Появился паттерн сарказма",
    "timeline_story_semantic_aggression_visible": "Появились агрессивные формулировки",
    "timeline_story_semantic_pressure_pattern": "Появился паттерн давления",
    "timeline_story_semantic_influence_pattern": "Появился паттерн влияния",
    "timeline_story_semantic_persuasion_visible": "Появилось убеждение",
    "timeline_story_semantic_possible_interest": "Признаки личной инициативы усилились",
    "timeline_story_semantic_body": "Зафиксирован смысловой паттерн общения.",
    "button_cancel_analysis": "Отменить анализ",
    "local_summary_long_history": "Это большой период истории, поэтому отчет разделяет общий фон и недавние изменения.",
    "local_summary_family_long_history": "Это большая семейная переписка: отчет отдельно смотрит общий фон, недавние изменения и нерешенные практические вопросы.",
    "local_finding_limited_positive_support": "В этой переписке пока мало признаков, которые позволили бы назвать общение устойчивым и взаимным.",
    "local_strength_reciprocal_initiation_title": "Инициатива распределена взаимно",
    "local_strength_reciprocal_initiation_explanation": "Несколько сессий начинались с разных сторон, а не только одним участником.",
    "local_strength_consistent_responses_title": "Ответы появляются регулярно",
    "local_strength_consistent_responses_explanation": "В переписке достаточно чередующихся сообщений, чтобы видеть устойчивый ритм ответа.",
    "question_metric_normalized": "Вы задали {count} прямых вопросов в {denominator} своих текстовых сообщениях — около {rate}%. Собеседник задавал вопросы примерно в {other_rate}% своих сообщений.",
    "question_metric_unanswered_observation": "{unanswered} прямых вопросов могли остаться без видимой реакции. Всего у вас {count} прямых вопросов в {denominator} текстовых сообщениях — около {rate}%.",
    "question_metric_unanswered_interpretation": "Это указывает на возможную проблему с завершением важных вопросов, но не доказывает намеренный уход от ответа.",
    "question_metric_alternative": "Часть вопросов могла быть риторической, закрытой вне переписки или не требовать отдельного ответа.",
    "question_metric_limitation": "Вопросы определены эвристически; ссылки, цитаты, код и повторная пунктуация исключаются.",
    "finding_title_unanswered_questions": "Часть вопросов остается без видимого завершения",
    "evidence_desc_explicit_sarcasm_label": "явная метка сарказма или иронии",
    "evidence_desc_normalized_question_rate": "доля прямых вопросов с учетом числа сообщений",
    "participation_balance_title": "Баланс участия",
    "participation_balance_similar_volume_length": "По объему и средней длине сообщений участие выглядит примерно равномерным. Это говорит о балансе активности, но не доказывает одинаковое внимание, теплоту или качество ответов.",
    "participant_you_longer_messages": "Ваши сообщения заметно длиннее в среднем.",
    "participant_other_longer_messages": "Сообщения собеседника заметно длиннее в среднем.",
    "score_explanation_title": "Почему {score}?",
    "score_explanation_title_unavailable": "Почему нет надежной оценки?",
    "score_positive_title": "Что подняло оценку",
    "score_negative_title": "Что снизило оценку",
    "score_unavailable_title": "Что не оценивалось",
    "score_positive_reciprocity": "участие по объему выглядит сбалансированным",
    "score_positive_initiative_balance": "инициатива распределена достаточно ровно",
    "score_positive_reply_consistency": "ответы выглядят достаточно стабильными",
    "score_positive_reply_quality": "большинство прямых вопросов получает видимую реакцию",
    "score_positive_respectfulness": "нет поддержанных признаков неуважительной формы",
    "score_positive_topic_continuation": "темы регулярно продолжаются",
    "score_positive_question_engagement": "вопросы чаще получают реакцию",
    "score_positive_planning_cooperation": "планы становятся конкретнее",
    "score_positive_emotional_acknowledgement": "эмоциональные сообщения получают признание",
    "score_negative_pressure_risk": "есть риск давления или повторных напоминаний",
    "score_negative_hostility": "есть поддержанные признаки враждебной формы",
    "score_negative_dismissiveness": "есть поддержанные признаки обесценивания",
    "score_negative_unanswered_question_rate": "часть вопросов остается без видимой реакции",
    "score_negative_sarcasm_intensity": "сарказм может мешать прямому ответу",
    "score_negative_work_task_clarity": "рабочие задачи сформулированы недостаточно ясно",
    "score_negative_work_questions": "часть рабочих вопросов не получила видимого завершения",
    "score_negative_work_clarification": "одни и те же рабочие вопросы требуют повторного уточнения",
    "score_negative_work_answer_completeness": "ответы не закрывают рабочий вопрос полностью",
    "score_negative_supported_sarcasm": "поддержанный сарказм мешает прямому рабочему ответу",
    "score_negative_hostile_sarcasm": "поддержанный враждебный сарказм мешает обсуждению",
    "score_negative_aggression": "есть подтвержденная агрессивная форма общения",
    "score_negative_supported_finding": "подтвержденный фактор снизил оценку",
    "score_low_initiative_balance": "инициатива распределена неравномерно",
    "score_low_reply_consistency": "ритм ответов нестабилен",
    "score_low_reply_quality": "качество видимых ответов выглядит слабым",
    "score_low_respectfulness": "форма общения снижает уважительность",
    "score_low_topic_continuation": "темы часто не получают продолжения",
    "score_low_question_engagement": "вопросы получают слабую реакцию",
    "score_low_planning_cooperation": "планы остаются неясными",
    "score_low_emotional_acknowledgement": "эмоциональные сообщения слабо признаются",
    "score_unavailable_respectfulness": "уважительность без анализа смысла оценена ограниченно",
    "score_unavailable_emotional_acknowledgement": "эмоциональное признание без анализа смысла недоступно",
    "score_unavailable_sarcasm_intensity": "сарказм недоступен без достаточных признаков",
    "score_unavailable_hostility": "враждебность недоступна без достаточных признаков",
    "score_unavailable_dismissiveness": "обесценивание недоступно без достаточных признаков",
    "score_explanation_balance_note": "Баланс количества сообщений не повысил оценку сам по себе, потому что он не отражает качество ответов.",
    "score_explanation_local_semantic_mode": "Оценка ограничена локальным режимом: он не понимает весь смысл сообщений.",
    "score_explanation_ai_semantic_mode": "Смысловые выводы использовали ИИ-анализ выбранной анонимизированной выборки.",
    "score_explanation_work_local_cap": "Оценка ограничена локальным рабочим режимом: он видит структуру, но не подтверждает качество всех решений.",
    "score_explanation_work_semantic_cap": "Оценка построена по рабочей эффективности и проверенным смысловым выводам.",
    "history_section_title": "Длинная история",
    "history_current_picture_title": "Текущая картина",
    "history_long_term_pattern_title": "Долгосрочный паттерн",
    "history_recent_change_title": "Недавнее изменение",
    "history_window_count": "История разделена на {count} сопоставимых окон.",
    "history_current_family": "В последнем окне семейная переписка содержит {messages} сообщений; важнее смотреть не только объем, но и завершение практических вопросов.",
    "history_current_work": "В последнем рабочем окне {messages} сообщений; прямые вопросы с вашей стороны составляют около {questions}% ваших сообщений.",
    "history_current_general": "В последнем окне переписка содержит {messages} сообщений; недавний период сравнивается с общим фоном.",
    "history_baseline_family_balanced": "За всю историю участие выглядит примерно равномерным ({messages} сообщений), но это не доказывает, что важные семейные вопросы всегда решаются.",
    "history_baseline_work_balanced": "За всю рабочую историю участие по объему примерно равномерное ({messages} сообщений), но эффективность зависит от ясности задач и завершения решений.",
    "history_baseline_balanced": "За всю историю участие выглядит примерно равномерным ({messages} сообщений), но объем сам по себе не равен качеству общения.",
    "history_baseline_uneven": "За всю историю больший видимый объем чаще приходится на сторону: {side} ({messages} сообщений).",
    "history_recent_limited": "Недавнее изменение пока нельзя сравнить надежно.",
    "history_recent_initiative_shift": "В последнем окне больше видимой активности приходится на сторону: {side}.",
    "history_recent_more_questions": "В последнем окне стало больше прямых вопросов относительно объема сообщений.",
    "history_recent_work_more_questions": "В последнем рабочем окне выросла доля прямых вопросов относительно объема сообщений.",
    "history_recent_more_pauses": "В последнем окне стало больше длинных пауз.",
    "history_recent_family_stable": "Недавний семейный ритм похож на предыдущий сегмент.",
    "history_recent_work_stable": "Существенных изменений нет: темп ответов, доля прямых вопросов и рабочие план-сигналы близки к предыдущему сегменту.",
    "history_recent_stable": "Недавний ритм похож на предыдущий сегмент.",
    "history_segmentation_limitation": "Сегменты показывают агрегаты и не содержат сырой текст сообщений.",
    "work_report_happening_title": "Что происходит",
    "work_report_you_title": "Как вы ведете рабочее общение",
    "work_report_other_title": "Как отвечает собеседник",
    "work_report_helps_title": "Что помогает работе",
    "work_report_blocks_title": "Что мешает",
    "work_report_changes_title": "Изменения",
    "work_report_data_title": "Данные и ограничения",
    "canonical_local_semantic_limitation": "Локальный режим видит только явные или повторяющиеся формулировки и не подтверждает скрытый смысл.",
    "canonical_title_general": "Поддержанный вывод",
    "canonical_title_sarcasm": "Сарказм требует осторожной интерпретации",
    "canonical_title_aggression": "Агрессивная форма требует прямых свидетельств",
    "canonical_title_influence": "Паттерн влияния требует контекста",
    "canonical_title_possible_interest": "Признаки интереса требуют осторожной интерпретации",
    "canonical_title_ambiguous_sarcasm": "Возможная ироничная или обесценивающая формулировка",
    "canonical_title_ambiguous_influence": "Возможный паттерн давления не подтвержден надежно",
    "canonical_observation_count": "Найдено свидетельств: {count}.",
    "canonical_observation_ambiguous_sarcasm": "Найдено {count} слабых локальных признаков, но они не подтверждают сарказм сами по себе.",
    "canonical_observation_ambiguous_influence": "Найдено {count} слабых локальных признаков влияния, но их недостаточно для уверенного вывода.",
    "canonical_interpretation_limited": "Вывод ограничен доступными данными.",
    "canonical_interpretation_local_ambiguous": "Это может быть смысловой паттерн, но локального режима недостаточно для уверенного вывода.",
    "canonical_interpretation_ambiguous_sarcasm": "Формулировки могут звучать иронично или обесценивающе, но локальный режим не может уверенно отделить сарказм от раздражения или привычного юмора.",
    "canonical_interpretation_ambiguous_influence": "Формулировка может усиливать давление, но по локальным признакам нельзя уверенно отделить это от неудачной просьбы.",
    "work_finding_unanswered_questions_title": "Рабочие вопросы не всегда закрываются",
    "work_finding_unanswered_questions_observation": "{unanswered} рабочих вопросов могли остаться без видимого завершения. Всего у вас {count} прямых вопросов в {denominator} текстовых сообщениях — около {rate}%.",
    "work_finding_unanswered_questions_interpretation": "Для рабочего чата это важно только как риск незавершенных решений, а не как доказательство игнорирования.",
    "work_finding_repeated_clarification_title": "Повторяются уточнения по рабочим вопросам",
    "work_finding_repeated_clarification_observation": "Найдено {count} явных уточнений по задачам или срокам.",
    "work_finding_repeated_clarification_interpretation": "Это указывает, что часть рабочих вопросов требует повторного прояснения.",
    "work_finding_task_clarity_title": "Задачи формулируются не полностью",
    "work_finding_task_clarity_observation": "Есть {tasks} рабочих упоминаний, но явных признаков ответственного, срока или решения значительно меньше ({clarity}).",
    "work_finding_task_clarity_interpretation": "Локально это выглядит как риск неясной постановки задачи, а не как доказательство плохой работы.",
    "work_finding_decision_completion_title": "Часть решений явно закрывается",
    "work_finding_decision_completion_observation": "Найдено {count} явных признаков решения, подтверждения или завершения.",
    "work_finding_decision_completion_interpretation": "Это поддерживает эффективность: часть рабочих обсуждений доходит до конкретного результата.",
    "work_finding_response_consistency_title": "Ответы идут регулярно",
    "work_finding_response_consistency_observation": "Найдено {count} чередующихся ответов между участниками.",
    "work_finding_response_consistency_interpretation": "Регулярный ритм помогает работе, но сам по себе не доказывает, что задачи закрываются.",
    "work_finding_alternative": "Часть рабочих решений могла быть закрыта вне переписки.",
    "work_finding_local_limitation": "Локальный анализ ищет явные рабочие маркеры и не понимает весь смысл решений.",
    "work_finding_history_scope_limitation": "Для длинной истории вывод относится к агрегированным периодам, а не к каждому эпизоду.",
    "advice_route_ambiguous_sarcasm_title": "Вернитесь к рабочему вопросу без спора о тоне",
    "advice_route_ambiguous_sarcasm_explanation": "Некоторые формулировки могут звучать иронично или обесценивающе. Если важный рабочий вопрос остался без ответа, вернитесь к нему прямо и без обсуждения тона.",
    "advice_route_ambiguous_sarcasm_example": "Давай отдельно зафиксируем решение по этому вопросу.",
    "advice_route_hostile_sarcasm_title": "Отделите форму от задачи",
    "advice_route_hostile_sarcasm_explanation": "Если уничижительная форма мешает рабочему обсуждению, обозначьте это и верните разговор к конкретной задаче.",
    "advice_route_hostile_sarcasm_example": "Такая форма мешает обсудить задачу. Давай вернемся к решению.",
    "advice_route_threat_title": "Остановите обсуждение при угрозах",
    "advice_route_threat_explanation": "Если есть прямые угрозы, сначала нужна граница безопасности; рабочую задачу обсуждайте только после прекращения такой формы.",
    "advice_route_threat_example": "Я не продолжаю обсуждение в форме угроз.",
    "advice_route_sarcasm_title": "Вернитесь к сути после шутки",
    "advice_route_sarcasm_explanation": "Если шутка заменяет ответ по задаче, спокойно верните разговор к сути и попросите зафиксировать решение.",
    "advice_route_sarcasm_example": "Давай отдельно зафиксируем решение по этому вопросу.",
    "advice_route_aggression_title": "Обозначьте границу формы общения",
    "advice_route_aggression_explanation": "Если появляются прямые оскорбления или агрессивные требования, обозначьте границу формы общения перед продолжением.",
    "advice_route_aggression_example": "Я готов обсуждать тему, но не в форме оскорблений.",
    "advice_route_pressure_title": "Не повторяйте просьбу после отказа",
    "advice_route_pressure_explanation": "После явного отказа повтор той же просьбы в другой форме может восприниматься как давление.",
    "advice_route_pressure_example": "Понял. Тогда скажи, какой вариант для тебя приемлем.",
    "advice_route_persuasion_title": "Оставляйте выбор явным",
    "advice_route_persuasion_explanation": "Убеждение работает честнее, когда аргумент понятен, а отказ остается допустимым.",
    "advice_route_persuasion_example": "Предлагаю так, потому что это быстрее. Если не подходит, выберем другой вариант.",
    "advice_route_question_title": "Повторите один важный вопрос отдельно",
    "advice_route_question_explanation": "Когда несколько вопросов теряются в длинной истории, выберите один актуальный и задайте его отдельным сообщением.",
    "advice_route_question_example": "Один вопрос: ты сможешь подтвердить это сегодня?",
    "advice_route_work_title": "Зафиксируйте задачу и срок",
    "advice_route_work_explanation": "В рабочих вопросах одним сообщением зафиксируйте задачу, ответственного, ожидаемый результат и срок.",
    "advice_route_work_example": "Задача: отправить финальный файл. Ответственный: Алексей. Срок: пятница 16:00.",
    "advice_route_interest_title": "Проясняйте интерес без давления",
    "advice_route_interest_explanation": "Если вы хотите показать личный интерес, сделайте одно ясное приглашение и оставьте место для честного ответа.",
    "advice_route_interest_example": "Мне хочется увидеться вдвоём. Тебе это интересно?",
    "advice_route_clarity_title": "Сформулируйте следующий шаг прямо",
    "advice_route_clarity_explanation": "Лучшее следующее сообщение должно содержать одну тему и один понятный вопрос или действие.",
    "advice_route_clarity_example": "Давай уточним один пункт: что делаем дальше?",
    "job_progress_title": "Ход анализа",
    "job_progress_chat": "Чат",
    "job_progress_status": "Статус",
    "job_progress_percent": "Прогресс",
    "job_progress_imported": "Загружено сообщений",
    "job_progress_elapsed": "Прошло",
    "job_progress_retrying": "Telegram временно не ответил. RelChat повторит попытку автоматически.",
    "job_progress_retrying_attempt": "Telegram временно не ответил. Повторная попытка {attempt} из {total}...",
    "job_status_queued": "В очереди",
    "job_status_loading": "Загрузка",
    "job_status_importing": "Загрузка сообщений",
    "job_status_analyzing": "Анализ",
    "job_status_loading_messages": "Загрузка сообщений",
    "job_status_analyzing_structure": "Структурный анализ",
    "job_status_analyzing_semantics": "Смысловой анализ",
    "job_status_building_report": "Сборка отчета",
    "job_status_retrying": "Повторная попытка",
    "job_status_completed": "Завершено",
    "job_status_failed": "Ошибка",
    "job_status_cancelled": "Отменено",
    "job_failed_title": "Анализ не завершился",
    "job_failure_reason": "Причина",
    "job_failure_retry_hint": "Можно повторить анализ или вернуться на экран чата.",
    "failure_no_messages": "За выбранный период сообщений не найдено.",
    "failure_telegram_temporary": "Telegram временно не ответил. RelChat повторит попытку автоматически.",
    "failure_telegram_temporary_final": "Telegram пока недоступен. Попробуйте повторить анализ через несколько минут.",
    "failure_telegram_auth": "Сессия Telegram больше не авторизована. Выполните повторный вход.",
    "failure_telegram_rate_limit": "Telegram попросил подождать перед продолжением. Повторите анализ позже.",
    "failure_network_dns": "Сеть или DNS сейчас недоступны. Проверьте подключение и повторите анализ.",
    "failure_provider_timeout": "Смысловой анализ не завершился вовремя. Если сообщения доступны локально, RelChat покажет структурный отчет.",
    "failure_provider_rate_limit": "Провайдер смыслового анализа временно ограничил запросы.",
    "failure_provider_invalid_response": "Смысловой анализ вернул неподходящий формат. Локальный структурный отчет безопаснее.",
    "failure_database_locked": "Локальная база данных временно занята. Повторите анализ.",
    "failure_validation_error": "Этот анализ нельзя выполнить с текущими настройками или доступом.",
    "failure_chat_inaccessible": "Этот чат недоступен через подключенный аккаунт Telegram.",
    "failure_cancelled": "Анализ отменен.",
    "failure_unknown": "Анализ остановился из-за внутренней ошибки.",
    "fingerprint_you_more_volume": "В этой переписке вы пишете чаще собеседника.",
    "fingerprint_other_more_volume": "В этой переписке собеседник пишет чаще вас.",
    "fingerprint_you_more_detail": "Ваши сообщения обычно подробнее сообщений собеседника.",
    "fingerprint_other_more_detail": "Собеседник обычно отвечает подробнее вас.",
    "fingerprint_you_more_starts": "После пауз разговор чаще возобновляется с вашей стороны.",
    "fingerprint_other_more_starts": "После пауз разговор чаще возобновляет собеседник.",
    "fingerprint_you_returns_after_pauses": "После длительных пауз вы чаще возвращаете разговор.",
    "fingerprint_other_returns_after_pauses": "После длительных пауз собеседник чаще возвращает разговор.",
    "fingerprint_you_more_questions": "Вы задаете прямые вопросы чаще: около {rate}% ваших текстовых сообщений против {other_rate}% у собеседника.",
    "fingerprint_other_more_questions": "Собеседник задает прямые вопросы чаще: около {rate}% своих текстовых сообщений против {user_rate}% у вас.",
    "fingerprint_consequence_balance_limited": "Это показывает баланс активности, но не качество внимания или ответов.",
    "fingerprint_consequence_you_carry": "Из-за этого поддержание обмена сильнее зависит от вас.",
    "fingerprint_consequence_other_carry": "Из-за этого ваша роль в этом периоде выглядит более реактивной.",
    "fingerprint_consequence_detail_work": "В рабочем чате подробность помогает только тогда, когда нужное действие легко найти.",
    "fingerprint_consequence_detail_general": "Это может поддерживать непрерывность, но прямые просьбы в длинных сообщениях легче пропустить.",
    "fingerprint_consequence_other_detail": "Это дает больше материала для ответа, но само по себе не доказывает лучшее понимание.",
    "fingerprint_consequence_initiative_you": "Непрерывность переписки из-за этого сильнее зависит от вас.",
    "fingerprint_consequence_initiative_other": "Непрерывность переписки из-за этого сильнее зависит от собеседника.",
    "fingerprint_consequence_user_continuity": "Это характерный паттерн продолжения именно в этом чате.",
    "fingerprint_consequence_other_continuity": "Это показывает, что собеседник не только отвечает внутри уже начатого обмена.",
    "fingerprint_consequence_questions_work": "Для работы важно не число вопросов само по себе, а приводят ли они к применимому ответу.",
    "fingerprint_consequence_questions_general": "Это помогает ясности, если вопросы получают ответы.",
    "fingerprint_consequence_other_questions": "Больше работы по уточнению берет на себя собеседник.",
    "fingerprint_recurring_finding": "Эта особенность повторяется: {finding}",
    "fingerprint_topic_work_tasks_work": "Рабочие задачи повторяются в этом периоде ({count} сообщений).",
    "fingerprint_topic_technical_work": "Техническое обсуждение повторяется в этом периоде ({count} сообщений).",
    "fingerprint_topic_planning_work": "Планирование или сроки повторяются в этом рабочем чате ({count} сообщений).",
    "fingerprint_topic_planning": "Планирование повторяется в этом периоде ({count} сообщений).",
    "fingerprint_topic_personal": "Личные темы повторяются в этом периоде ({count} сообщений).",
    "fingerprint_topic_support": "Поддержка или просьбы о помощи повторяются в этом периоде ({count} сообщений).",
    "fingerprint_topic_family_obligations": "Семейные обязанности повторяются в этом периоде ({count} сообщений).",
    "fingerprint_consequence_topic_work": "Поэтому ясность задачи важнее количества сообщений.",
    "fingerprint_consequence_topic_general": "Поэтому переписку нельзя считать единым одинаковым стилем на все темы.",
    "fingerprint_consequence_cross_chat": "Сравнение использует только агрегаты и не раскрывает другие чаты.",
    "fingerprint_consequence_recent_stability": "Недавняя структура близка к предыдущему сопоставимому сегменту.",
    "fingerprint_consequence_recent_change": "Последний сегмент важно читать на фоне более длинной истории.",
    "fingerprint_uncertainty_low_messages": "Сообщений недостаточно для сильного индивидуального вывода.",
    "fingerprint_uncertainty_local_semantics": "Локальный анализ видит структуру, но не может надежно оценить полный смысл ответов.",
    "fingerprint_uncertainty_not_enough_distinctive": "Этого недостаточно для индивидуального вывода.",
    "fingerprint_uncertainty_no_history_comparison": "Для этого отчета нет надежного сравнения с предыдущим периодом.",
    "fingerprint_uncertainty_rebuilt_without_messages": "Этот отпечаток переписки восстановлен по подтвержденным выводам отчета, а не по всем локальным сообщениям.",
    "individual_distinctive_title": "Что отличает эту переписку",
    "individual_headline_work_regular_unclear": "Рабочее обсуждение идет регулярно, но решения не всегда фиксируются ясно.",
    "individual_headline_work_decisions": "Часть рабочих решений явно доводится до завершения.",
    "individual_headline_work_questions_open": "Рабочие вопросы появляются, но часть остается открытой.",
    "individual_headline_work_regular_limited": "Рабочая переписка регулярна, но локальный анализ не подтверждает качество решений.",
    "individual_headline_work_limited": "Этот рабочий отчет ограничен структурой, пока нет более ясных признаков по задачам.",
    "individual_headline_questions_open": "Главная проблема не в активности, а в незавершенных вопросах.",
    "individual_headline_interest_cautious": "Есть признаки интереса, но чувства не доказаны.",
    "individual_headline_sarcasm": "Тон важен: сарказм меняет то, как завершаются темы.",
    "individual_headline_aggression": "Форма конфликта — главный вопрос в этой переписке.",
    "individual_headline_you_resume": "После пауз разговор обычно возобновляется с вашей стороны.",
    "individual_headline_you_detail": "Вы даете больше деталей, собеседник отвечает короче.",
    "individual_headline_limited": "Этого недостаточно для индивидуального вывода.",
    "individual_headline_family": "Семейный контакт регулярный, но важнее смотреть на завершение практических вопросов.",
    "individual_headline_friendship": "Дружеский паттерн определяется продолжением тем, а не только числом сообщений.",
    "individual_headline_romantic": "Видимый интерес зависит от взаимности, а не от объема сообщений.",
    "individual_headline_general": "Отчет строится вокруг самого ясного паттерна именно этой переписки.",
    "individual_overall_work_local": "Переписка достаточно регулярна, чтобы описать структуру. {detail} Локальный режим не может подтвердить, закрывал ли каждый ответ рабочую задачу.",
    "individual_overall_two_patterns": "{first} {second}",
    "individual_overall_limited": "Этого недостаточно для индивидуального отчета.",
    "individual_dynamic_work_topic": "В рабочих вопросах {detail}",
    "individual_user_role_work": "В этом рабочем чате {detail}",
    "individual_user_role_general": "В этой переписке {detail}",
    "individual_other_role_work": "Рабочий паттерн собеседника отличается: {detail}",
    "individual_other_role_general": "Паттерн собеседника отличается: {detail}",
    "individual_history_segmented_limited": "Полная история разделена на {count} окон; показаны только агрегированные изменения.",
    "individual_uncertainty_default": "Причину паттерна нельзя определить только по сообщениям.",
    "feedback_omitted_no_actionable_finding": "Нет достаточно поддержанной практической проблемы для рекомендации.",
    "feedback_omitted_weak_semantic": "Слабого локального смыслового признака недостаточно для совета.",
    "feedback_style_fit_work_limited": "Локальный рабочий отчет не показывает явной проблемы в вашей формулировке.",
    "feedback_style_fit_limited": "Выбранный период не показывает явной проблемы в вашей формулировке.",
    "feedback_no_action_work": "Сейчас нет очевидной необходимости менять стиль рабочего общения.",
    "feedback_no_action_general": "Сейчас нет очевидной необходимости менять стиль общения.",
    "feedback_work_action_first_title": "Поставьте нужное действие в начало",
    "feedback_work_action_first_reason": "Вы уже даете контекст, но в этом чате практическая просьба может теряться. Сначала напишите нужное действие, потом пояснение.",
    "feedback_work_action_first_example": "Сначала подтвердите ответственного и срок. Контекст: от этого зависит релиз.",
    "feedback_work_task_title": "Зафиксируйте рабочий пункт одним сообщением",
    "feedback_work_task_reason": "Поддержанная проблема связана с ясностью задачи, поэтому следующее сообщение должно назвать задачу, ответственного, ожидаемый результат и срок.",
    "feedback_work_task_example": "Задача: отправить финальный файл. Ответственный: Алексей. Результат: согласованный PDF. Срок: пятница 16:00.",
    "feedback_work_question_title": "Повторите один рабочий вопрос отдельно",
    "feedback_work_question_reason": "Проблема не в количестве сообщений, а в том, что рабочий вопрос может остаться незавершенным.",
    "feedback_work_question_example": "Один вопрос: сможешь подтвердить срок сегодня?",
    "feedback_question_title": "Повторите один актуальный вопрос",
    "feedback_question_reason": "Отдельный вопрос проще заметить и закрыть, чем уточнение внутри длинного сообщения.",
    "feedback_question_example": "Один момент всё ещё нужно прояснить: мы это делаем или нет?",
    "feedback_work_clarification_title": "Остановите цикл уточнений",
    "feedback_work_clarification_reason": "Повторяется именно уточнение, поэтому полезный шаг — назвать точку решения.",
    "feedback_work_clarification_example": "Давай решим один пункт: кто отвечает и к какому сроку?",
    "feedback_sarcasm_title": "Вернитесь к теме после шутки",
    "feedback_sarcasm_reason": "Если сарказм заменяет прямой ответ, спор о шутке обычно уводит дальше от сути. Вернитесь к самому вопросу.",
    "feedback_sarcasm_example": "Я понял шутку, но мне всё ещё нужно решение по этому пункту.",
    "feedback_aggression_title": "Обозначьте границу формы",
    "feedback_aggression_reason": "Поддержанная проблема — прямая агрессивная формулировка, поэтому сначала стоит обозначить форму общения.",
    "feedback_aggression_example": "Я готов обсуждать вопрос, но не в форме оскорблений.",
    "feedback_pressure_title": "Оставьте возможность отказа",
    "feedback_pressure_reason": "Поддержанный паттерн давления означает, что повтор той же просьбы может затруднять отказ.",
    "feedback_pressure_example": "Понял. Если этот вариант не подходит, скажи, что будет приемлемо.",
    "feedback_interest_title": "Проясните интерес один раз",
    "feedback_interest_reason": "В чате есть возможные признаки интереса, но они не доказывают чувства. Прямое приглашение честнее намеков.",
    "feedback_interest_example": "Мне хочется встретиться вдвоем. Тебе это интересно?",
    "feedback_clarity_title": "Проясните следующий шаг",
    "feedback_clarity_reason": "Самое поддержанное улучшение — прямо назвать следующее действие.",
    "feedback_clarity_example": "Давай уточним один пункт: что должно произойти дальше?",
    "participation_scope_selected_period": "В выбранном периоде",
    "participation_scope_full_history": "По всей истории",
    "participation_scope_recent_window": "В недавнем окне",
    "participation_scope_recurring": "В сопоставимых периодах",
    "participation_summary_balanced": "{scope} участие сбалансировано: у вас {you} сообщений, у собеседника {other}. Это показывает баланс активности, но не доказывает одинаковое внимание, теплоту или качество ответов.",
    "participation_summary_you_more": "{scope} вы пишете чаще собеседника: около {share}% сообщений с вашей стороны.",
    "participation_summary_other_more": "{scope} собеседник пишет чаще: около {share}% сообщений с его стороны.",
    "participation_summary_insufficient": "{scope} сообщений недостаточно для надежного сравнения участия.",
    "participation_scoped_difference": "{full} {recent}",
    "history_scope_note": "Общий фон построен по {total} сообщениям. Недавние изменения оценивались по последним {recent} сообщениям.",
    "individual_opening_with_participation": "{participation} {quality} {uncertainty}",
    "score_explanation_low_independence": "Надежная оценка не показана: поддержано слишком мало независимых измерений общения.",
    "report_created": "Создан",
    "report_messages": "Сообщений проанализировано",
    "report_confidence": "Уверенность",
    "report_completeness": "Полнота",
}
